'use strict';

// ─────────────────────────────────────────────────────────────
// 스킬 카드 (PHASE 6 신스키마 — 2026-05-05 마이그레이션)
// 5필드 + 메타. 옛 effect/attackType/targetType/damage/heal/cost 등 모두 폐기.
// kind: spell-target / spell-aoe / attach-hero / attach-unit
// ─────────────────────────────────────────────────────────────

RoF.Data.SKILLS = Object.freeze([
  // 2026-05-17 사용자 컨펌 v2 갤러리 — effects 배열 채움 + ability 명확화 ("영구" → "보드 유지"/"이 매치 동안")
  {id:'sk_power',     name:'끓어오르는 힘', role:'attack',  rarity:'bronze',    kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:1, keywords:[], ability:'지정 아군 1체 ATK +1 (보드 유지)', desc:'', ATK:1, aiHint:'pump', upgradeChoices:[], effects:[{op:'attach_buff',target:'ally_one',stat:'ATK',amount:1}]},
  {id:'sk_shield',    name:'방패 사용자', role:'defense', rarity:'bronze',    kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:1, keywords:[], ability:'지정 아군 1체 DEF +1 (1턴 보호막)', desc:'', HP:0, DEF:1, defTurns:1, aiHint:'defensive', upgradeChoices:[], effects:[{op:'shield',target:'ally_one',amount:1,turns:1}]},
  {id:'sk_heal',      name:'체력 단련', role:'support', rarity:'bronze',    kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:1, keywords:[], ability:'자기 영웅 최대 HP +1 (이 매치 동안)', desc:'', HP:1, aiHint:'support', upgradeChoices:[], effects:[{op:'attach_buff',target:'hero',stat:'HP',amount:1}]},
  {id:'sk_swift',     name:'하체 단련', role:'attack',  rarity:'bronze',    kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:1, keywords:[], ability:'자기 영웅 최대 HP +1 (이 매치 동안)', desc:'', ATK:0, HP:1, aiHint:'support', upgradeChoices:[], effects:[{op:'attach_buff',target:'hero',stat:'HP',amount:1}]},
  {id:'sk_tough',     name:'정밀 공격', role:'crit',    rarity:'bronze',    kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, keywords:[], ability:'모든 아군 원거리 유닛 ATK +1 (보드 유지)', desc:'', ATK:1, aiHint:'pump', upgradeChoices:[], effects:[{op:'aura',filter:{type:'role_eq',value:'ranged'},stat:'ATK',amount:1}]},
  {id:'sk_focus',     name:'집중', role:'support', rarity:'bronze',    kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:1, keywords:[], ability:'카드 1장 드로우', desc:'', ATK:0, aiHint:'support', upgradeChoices:[], effects:[{op:'_todo',_todo:'draw_1'}]},
  {id:'sk_rage',      name:'광전사의외침', role:'attack',  rarity:'silver',    kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, keywords:[], ability:'수호자거나 근접인 아군 ATK +1 (보드 유지)', desc:'', ATK:1, aiHint:'pump', upgradeChoices:[], effects:[{op:'aura',filter:{type:'taunt_or_role_eq',value:'melee'},stat:'ATK',amount:1}]},
  {id:'sk_boil',      name:'끓어오름', role:'attack',  rarity:'silver',    kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, keywords:[], ability:'지정 아군 1체 ATK +2 (보드 유지)', desc:'', ATK:2, aiHint:'pump', upgradeChoices:[], effects:[{op:'attach_buff',target:'ally_one',stat:'ATK',amount:2}]},
  {id:'sk_evasion',   name:'잔상술', role:'defense', rarity:'silver',    kind:'attach-hero',  dmgType:'magic', magicKind:'debuff', NEED_SOUL:1, keywords:[], ability:'지정 적 1체 피해 1 + 카드 1장 드로우', desc:'', ATK:1, aiHint:'control', upgradeChoices:[], effects:[{op:'damage',target:'enemy_one',amount:1},{op:'_todo',_todo:'draw_1'}]},
  {id:'sk_energize',  name:'활력충전', role:'support', rarity:'silver',    kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, keywords:[], ability:'지정 아군 1체 최대 HP +2 (이 매치 동안)', desc:'', HP:2, aiHint:'support', upgradeChoices:[], effects:[{op:'attach_buff',target:'ally_one',stat:'HP',amount:2}]},
  {id:'sk_cleave',    name:'일섬', role:'attack',  rarity:'silver',    kind:'spell-target', dmgType:'melee', NEED_SOUL:2, keywords:[], ability:'지정 적 1체 피해 2', desc:'', ATK:2, aiHint:'finisher', upgradeChoices:[], effects:[{op:'damage',target:'enemy_one',amount:2}]},
  {id:'sk_ironwill',  name:'불굴', role:'defense', rarity:'silver',    kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, keywords:[], ability:'지정 아군 1체 HP +1 + DEF +1 (1턴)', desc:'', HP:1, ATK:0, DEF:1, defTurns:1, aiHint:'defensive', upgradeChoices:[], effects:[{op:'attach_buff',target:'ally_one',stat:'HP',amount:1},{op:'shield',target:'ally_one',amount:1,turns:1}]},
  {id:'sk_prayer',    name:'기도', role:'support', rarity:'silver',    kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, keywords:[], ability:'지정 아군 1체 HP 2 회복', desc:'', HP:2, aiHint:'support', upgradeChoices:[], effects:[{op:'heal',target:'ally_one',amount:2}]},
  {id:'sk_reflex',    name:'반사신경', role:'defense', rarity:'silver',    kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, keywords:[], ability:'지정 아군 1체 DEF +2 (2턴 보호막)', desc:'', HP:0, DEF:2, defTurns:2, aiHint:'defensive', upgradeChoices:[], effects:[{op:'shield',target:'ally_one',amount:2,turns:2}]},
  // sk_crit_edge (급소연마) — 2026-05-27 폐기: 자산 미공급 (사용자 동의)
  {id:'sk_fortress',  name:'철벽', role:'defense', rarity:'gold',      kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:3, keywords:[], ability:'지정 아군 1체 DEF +3 (3턴 보호막)', desc:'', HP:0, defTurns:3, DEF:3, aiHint:'defensive', upgradeChoices:[], effects:[{op:'shield',target:'ally_one',amount:3,turns:3}]},
  {id:'sk_revive',    name:'부활축복', role:'support', rarity:'gold',      kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:4, keywords:[], ability:'지정 아군 사망 시 즉시 부활. 전설+ 불가', desc:'', aiHint:'sac', upgradeChoices:[], effects:[{op:'_todo',_todo:'revive_on_death',condition:{rarity_below:'legendary'}}]},
  {id:'sk_bloodlust', name:'피의갈증', role:'attack',  rarity:'gold',      kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:3, keywords:[], ability:'지정 아군 1체 ATK +3 (보드 유지)', desc:'', ATK:3, aiHint:'pump', upgradeChoices:[], effects:[{op:'attach_buff',target:'ally_one',stat:'ATK',amount:3}]},
  {id:'sk_mirage',    name:'신기루', role:'defense', rarity:'gold',      kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, keywords:[], ability:'카드 2장 드로우', desc:'', aiHint:'support', upgradeChoices:[], effects:[{op:'_todo',_todo:'draw_2'}]},
  {id:'sk_warhorn',   name:'전쟁의나팔', role:'support', rarity:'gold',      kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:3, keywords:[], ability:'모든 아군 ATK +1 (이 매치 동안)', desc:'', ATK:1, aiHint:'pump', upgradeChoices:[], effects:[{op:'attach_buff',target:'ally_all',stat:'ATK',amount:1}]},
  {id:'sk_execute',   name:'처형', role:'attack',  rarity:'gold',      kind:'spell-target', dmgType:'magic', magicKind:'debuff', NEED_SOUL:4, keywords:[], ability:'지정 적 1체 즉시 처형. 전설+ 불가', desc:'', aiHint:'finisher', upgradeChoices:[], effects:[{op:'_todo',_todo:'instant_kill',condition:{rarity_below:'legendary'},target:'enemy_one'}]},
  {id:'sk_aura',      name:'수호오라', role:'support', rarity:'gold',      kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:3, keywords:[], ability:'모든 아군 DEF +1 (2턴 보호막)', desc:'', HP:0, DEF:1, defTurns:2, aiHint:'defensive', upgradeChoices:[], effects:[{op:'shield',target:'ally_all',amount:1,turns:2}]},
  {id:'sk_handoff',   name:'핸드오프', role:'support', rarity:'gold',      kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:3, keywords:[], ability:'매 턴 카드 1장 더 드로우', desc:'', aiHint:'support', upgradeChoices:[], effects:[{op:'_todo',_todo:'persistent_extra_draw_per_turn'}]},
  {id:'sk_berserk',   name:'광폭화', role:'attack',  rarity:'legendary', kind:'attach-hero',  dmgType:'magic', magicKind:'debuff', NEED_SOUL:5, keywords:[], ability:'지정 아군 1체 ATK +5 + 자기 피해 -1', desc:'', ATK:5, aiHint:'pump', upgradeChoices:[], effects:[{op:'attach_buff',target:'ally_one',stat:'ATK',amount:5},{op:'attach_debuff',target:'ally_one',stat:'HP',amount:1}]},
  {id:'sk_transcend', name:'초월', role:'support', rarity:'legendary', kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:5, keywords:[], ability:'지정 아군 1체 HP +5 (이 매치 동안)', desc:'', HP:5, aiHint:'support', upgradeChoices:[], effects:[{op:'attach_buff',target:'ally_one',stat:'HP',amount:5}]},
  {id:'sk_invincible',name:'무적', role:'defense', rarity:'legendary', kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:5, keywords:[], ability:'지정 아군 1체 공격/반격 그대로 반사 (보드 유지)', desc:'', aiHint:'defensive', upgradeChoices:[], effects:[{op:'_todo',_todo:'reflect_all_damage',target:'ally_one'}]},
  {id:'sk_godslayer', name:'신살', role:'attack',  rarity:'legendary', kind:'spell-target', dmgType:'magic', magicKind:'debuff', NEED_SOUL:6, keywords:[], ability:'지정 적 1체 즉시 처형. 신 등급 불가', desc:'', aiHint:'finisher', upgradeChoices:[], effects:[{op:'_todo',_todo:'instant_kill',condition:{rarity_below:'divine'},target:'enemy_one'}]},
  {id:'sk_resurrection',name:'부활의성배', role:'support', rarity:'legendary', kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:6, keywords:[], ability:'지정 아군 사망 시 즉시 부활. 신 등급 불가', desc:'', aiHint:'sac', upgradeChoices:[], effects:[{op:'_todo',_todo:'revive_on_death',condition:{rarity_below:'divine'}}]},
  {id:'sk_shadowstep',name:'그림자걸음', element:'dark', role:'defense', rarity:'legendary', kind:'spell-target', dmgType:'magic', magicKind:'debuff', NEED_SOUL:5, keywords:[], ability:'지정 적 1체 피해 6 + 자기 다음 1회 회피', desc:'', ATK:5, aiHint:'finisher', upgradeChoices:[], effects:[{op:'damage',target:'enemy_one',amount:6},{op:'stealth',target:'self',turns:1}]},
  {id:'sk_dragonheart',name:'용의심장', role:'support', rarity:'legendary', kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:5, keywords:[], ability:'지정 아군 1체 HP +2 + ATK +2 + DEF +2 (2턴)', desc:'', HP:2, ATK:2, DEF:2, defTurns:2, aiHint:'pump', upgradeChoices:[], effects:[{op:'attach_buff',target:'ally_one',stat:'HP',amount:2},{op:'attach_buff',target:'ally_one',stat:'ATK',amount:2},{op:'shield',target:'ally_one',amount:2,turns:2}]},
  {id:'sk_flame_arrow', name:'불꽃 화살', element:'fire', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:1, keywords:[], ability:'지정 적 1체 화염 피해 1 (수호자 무시)', desc:'', ATK:1, aiHint:'control', upgradeChoices:[], effects:[{op:'damage',target:'enemy_one',amount:1,pierce:'taunt'}]},
  {id:'sk_healing_light', name:'치유의 빛', element:'holy', role:'support', rarity:'bronze', kind:'spell-target', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, keywords:[], ability:'지정 아군 1체 HP +1 회복', desc:'', HP:1, aiHint:'support', upgradeChoices:[], effects:[{op:'heal',target:'ally_one',amount:1}]},
  {id:'sk_thunder_arrow', name:'번개', element:'lightning', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'magic', magicKind:'debuff', NEED_SOUL:1, keywords:[], ability:'지정 적 1체 번개 피해 1', desc:'', ATK:1, upgradeChoices:[], effects:[{op:'damage',target:'enemy_one',amount:1}]},
  {id:'sk_hex', name:'저주', element:'dark', role:'defense', rarity:'bronze', kind:'spell-target', dmgType:'magic', magicKind:'debuff', NEED_SOUL:1, keywords:[], ability:'지정 적 1체 암흑 피해 1', desc:'', ATK:1, aiHint:'control', upgradeChoices:[], effects:[{op:'damage',target:'enemy_one',amount:1}]},
  {id:'sk_ember', name:'잉걸', element:'fire', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'magic', magicKind:'debuff', NEED_SOUL:1, keywords:[], ability:'지정 적 1체 화염 피해 1', desc:'', ATK:1, upgradeChoices:[], effects:[{op:'damage',target:'enemy_one',amount:1}]},
  {id:'sk_minor_curse', name:'작은 저주', element:'dark', role:'defense', rarity:'bronze', kind:'attach-unit', dmgType:'magic', magicKind:'debuff', NEED_SOUL:1, keywords:[], ability:'지정 적 1체 화상 (매 턴 피해 1, 2턴)', desc:'', ATK:1, aiHint:'control', upgradeChoices:[], effects:[{op:'burn',target:'enemy_one',amount:1,turns:2}]},
  {id:'sk_spark_blast', name:'불똥 폭발', element:'fire', role:'attack', rarity:'bronze', kind:'spell-aoe', dmgType:'magic', magicKind:'debuff', NEED_SOUL:1, keywords:[], ability:'모든 적 화염 피해 1', desc:'', ATK:1, aiHint:'aoe-priority', upgradeChoices:[], effects:[{op:'damage',target:'enemy_all',amount:1}]},
  {id:'sk_tidal_crash', name:'파도 강타', element:'water', role:'attack', rarity:'silver', kind:'spell-target', dmgType:'magic', magicKind:'debuff', NEED_SOUL:2, keywords:[], ability:'지정 적 1체 물 피해 2', desc:'', ATK:2, aiHint:'finisher', upgradeChoices:[], effects:[{op:'damage',target:'enemy_one',amount:2}]},
  {id:'sk_earth_bulwark', name:'대지 방벽', element:'earth', role:'defense', rarity:'silver', kind:'attach-unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:2, keywords:[], ability:'지정 아군 1체 DEF +2 (2턴 보호막)', desc:'', HP:0, DEF:2, defTurns:2, aiHint:'defensive', upgradeChoices:[], effects:[{op:'shield',target:'ally_one',amount:2,turns:2}]},
  {id:'sk_chain_lightning', name:'번개 사슬', element:'lightning', role:'attack', rarity:'silver', kind:'spell-aoe', dmgType:'magic', magicKind:'debuff', NEED_SOUL:2, keywords:[], ability:'모든 적 번개 피해 2', desc:'', ATK:2, aiHint:'aoe-priority', upgradeChoices:[], effects:[{op:'damage',target:'enemy_all',amount:2}]},
  {id:'sk_dark_curse', name:'암흑 저주', element:'dark', role:'defense', rarity:'silver', kind:'attach-unit', dmgType:'magic', magicKind:'debuff', NEED_SOUL:2, keywords:[], ability:'지정 적 1체 암흑 지속피해 1 (2턴)', desc:'', ATK:2, aiHint:'control', upgradeChoices:[], effects:[{op:'burn',target:'enemy_one',element:'dark',amount:1,turns:2}]},
  {id:'sk_inferno_blast', name:'화염 폭발', element:'fire', role:'attack', rarity:'silver', kind:'spell-target', dmgType:'magic', magicKind:'debuff', NEED_SOUL:2, keywords:[], ability:'지정 적 1체 화염 피해 2', desc:'', ATK:2, aiHint:'finisher', upgradeChoices:[], effects:[{op:'damage',target:'enemy_one',amount:2}]},
  {id:'sk_herb_pack', name:'약초 꾸러미', element:'holy', role:'support', rarity:'silver', kind:'spell-target', dmgType:'magic', magicKind:'buff', NEED_SOUL:2, keywords:[], ability:'지정 아군 1체 HP +2 회복', desc:'', HP:2, aiHint:'support', upgradeChoices:[], effects:[{op:'heal',target:'ally_one',amount:2}]},
  {id:'sk_blessing_light', name:'축복의 빛', element:'holy', role:'support', rarity:'gold', kind:'spell-aoe', dmgType:'magic', magicKind:'buff', NEED_SOUL:3, keywords:[], ability:'모든 아군 HP +3 회복', desc:'', HP:3, aiHint:'support', upgradeChoices:[], effects:[{op:'heal',target:'ally_all',amount:3}]},

  // ─────────────────────────────────────────────────────────────
  // PHASE 6 유닛-스킬 패키지 (2026-05-06 기획변경 — design/phase6_unit_skill_bundle.md)
  // 11개 유닛에 종속된 49 고유 스킬. bundledByUnit 필드로 양방향 검증.
  // 모든 등급 = bronze (사용자 결정), kind 분류는 파일명 효과 기반 자동.
  // ─────────────────────────────────────────────────────────────

  // 늑대 (wolf) — 3
  {id:'sk_wolf_basic_attack', name:'송곳니', element:'earth', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'melee', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적에게 피해 + 1', desc:'', bundledByUnit:'wolf', unlockLevel:1, transferable:false, upgradeChoices:[{id:'a_deep', name:'깊게 무는 송곳니', ability:'적 1체에게 3 피해', effects:[{op:'damage', target:'enemy_one', amount:3}]},{id:'b_rend', name:'살을 찢는 송곳니', ability:'적 1체 1 피해 + 화상 1 (2턴)', effects:[{op:'damage', target:'enemy_one', amount:1},{op:'burn', target:'enemy_one', amount:1, turns:2}]}], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_wolf_summon', name:'무리 부르기', element:'earth', role:'support', rarity:'bronze', kind:'unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:1, HP:1, keywords:[], ability:'늑대 1마리를 보드에 소환 (HP 1 / ATK 1)', desc:'', bundledByUnit:'wolf', unlockLevel:2, transferable:false, upgradeChoices:[{id:'a_pack', name:'큰 무리', ability:'늑대 2마리 소환 (각 HP1/ATK1)', effects:[{op:'summon', amount:2, boardCap:6, stats:{HP:1, ATK:1}}]},{id:'b_alpha', name:'사나운 우두머리', ability:'늑대 1마리 소환 (HP2/ATK2/수호자)', effects:[{op:'summon', stats:{HP:2, ATK:2}, keywords:['taunt']}]}], effects:[{op:'summon', stats:{HP:1, ATK:1}}]},
  {id:'sk_wolf_natural_heal', name:'자연 치유', element:'earth', role:'support', rarity:'bronze', kind:'attach-unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:1, keywords:[], ability:'늑대 HP + 1 을 증가시킵니다.', desc:'', bundledByUnit:'wolf', unlockLevel:3, transferable:false, upgradeChoices:[{id:'a_vigor', name:'왕성한 생명력', ability:'늑대 HP +2 (매턴)', effects:[{op:'tick_heal', target:'ally_one', amount:2, perTurn:true}]},{id:'b_bond', name:'무리의 결속', ability:'아군 전체 HP +1 (매턴)', effects:[{op:'tick_heal', target:'ally_all', amount:1, perTurn:true}]}], effects:[{op:'tick_heal', target:'ally_one', amount:1, perTurn:true}]},

  // 사냥꾼 (hunter) — 5
  {id:'sk_hunter_basic_attack', name:'일반 사격', element:'earth', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'지정한 적에게 피해 +1 ', desc:'', bundledByUnit:'hunter', unlockLevel:1, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_hunter_hound_strike', name:'사냥개 공격', element:'earth', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'지정한 적에게 피해 +1 ', desc:'', bundledByUnit:'hunter', unlockLevel:2, transferable:true, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_hunter_summon_bear', name:'곰 소환', element:'earth', role:'defense', rarity:'bronze', kind:'unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:1, HP:2, keywords:['taunt'], ability:'곰 1마리 보드 소환 (HP 2 / ATK 1 / 수호자)', desc:'', bundledByUnit:'hunter', unlockLevel:3, transferable:true, upgradeChoices:[], effects:[{op:'summon', stats:{HP:2, ATK:1}, keywords:['taunt']}]},
  {id:'sk_hunter_summon_wolf', name:'늑대 소환', element:'earth', role:'attack', rarity:'bronze', kind:'unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:1, HP:1, keywords:[], ability:'늑대 1마리 보드 소환 (HP 1 / ATK 1)', desc:'', bundledByUnit:'hunter', unlockLevel:4, transferable:true, upgradeChoices:[], effects:[{op:'summon', stats:{HP:1, ATK:1}}]},
  {id:'sk_hunter_mark', name:'사냥꾼의 징표', element:'earth', role:'attack', rarity:'bronze', kind:'attach-unit', dmgType:'magic', magicKind:'debuff', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에 부착: 1턴간 모든 공격 +1 추가 피해', desc:'', bundledByUnit:'hunter', unlockLevel:5, transferable:false, upgradeChoices:[], effects:[{op:'attach_marker', target:'enemy_one', amount:1, turns:1, _todo:'all_attacks_bonus_dmg'}]},

  // 약초사 (herbalist) — 4
  {id:'sk_herbalist_first_aid', name:'응급 처치', element:'earth', role:'support', rarity:'bronze', kind:'spell-target', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:1, keywords:[], ability:'아군 1체 HP +1', desc:'', bundledByUnit:'herbalist', unlockLevel:1, transferable:false, upgradeChoices:[], effects:[{op:'heal', target:'ally_one', amount:1}]},
  {id:'sk_herbalist_heal_aura', name:'치유 강화', element:'earth', role:'support', rarity:'bronze', kind:'attach-hero', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:1, keywords:[], ability:'아군 체력증가 + 1', desc:'', bundledByUnit:'herbalist', unlockLevel:2, transferable:false, upgradeChoices:[], effects:[{op:'modifier', stat:'heal', amount:1, turns:1, _todo:'global_heal_modifier'}]},
  {id:'sk_herbalist_heal_atk_aura', name:'회복+공격 강화', element:'earth', role:'support', rarity:'bronze', kind:'attach-hero', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:0, keywords:[], ability:'약초사가 존재하는 한 모든 체력 증가/치료/회복 효과 +1', desc:'', bundledByUnit:'herbalist', unlockLevel:3, transferable:false, upgradeChoices:[], effects:[{op:'modifier', stat:'heal', amount:1, turns:1, _todo:'global_heal_modifier'},{op:'attach_buff', target:'hero', stat:'ATK', amount:1, turns:1}]},
  {id:'sk_herbalist_sleep_powder', name:'수면 가루', element:'earth', role:'defense', rarity:'bronze', kind:'spell-target', dmgType:'magic', magicKind:'debuff', NEED_SOUL:1, ATK:0, HP:0, keywords:[], ability:'적 1체 1턴 스턴', desc:'', bundledByUnit:'herbalist', unlockLevel:4, transferable:false, upgradeChoices:[], effects:[{op:'stun', target:'enemy_one', turns:1}]},

  // 보병 (infantry) — 4
  {id:'sk_infantry_basic_attack', name:'일반 공격', element:'earth', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'melee', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해', desc:'', bundledByUnit:'infantry', unlockLevel:1, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_infantry_shield_block', name:'방패 막기', element:'earth', role:'defense', rarity:'bronze', kind:'attach-unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:0, DEF:2, defTurns:1, keywords:[], ability:'자신에게 보호막 +2 (1턴)', desc:'', bundledByUnit:'infantry', unlockLevel:2, transferable:false, upgradeChoices:[], effects:[{op:'shield', target:'self', amount:2, turns:1}]},
  {id:'sk_infantry_reorganize', name:'재정비', element:'earth', role:'support', rarity:'bronze', kind:'attach-unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'아군 1체 ATK +1 ', desc:'', bundledByUnit:'infantry', unlockLevel:3, transferable:false, upgradeChoices:[], effects:[{op:'attach_buff', target:'ally_one', stat:'ATK', amount:1}]},
  {id:'sk_infantry_anti_lancer', name:'창병 격파', element:'earth', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'melee', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적에게 피해 + 1 (창병 유닛일 경우 피해 2배)', desc:'', bundledByUnit:'infantry', unlockLevel:4, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:4, condition:{type:'id_contains', value:'lancer'}}]},

  // 민병 (militia) — 4
  {id:'sk_militia_thrust', name:'찌르기', element:'earth', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'melee', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해', desc:'', bundledByUnit:'militia', unlockLevel:1, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_militia_harvest', name:'벼 수확', element:'earth', role:'support', rarity:'bronze', kind:'attach-hero', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:0, keywords:[], ability:'다음 카드의 NEED_SOUL -1', desc:'', bundledByUnit:'militia', unlockLevel:2, transferable:false, upgradeChoices:[], effects:[{op:'next_card_discount', amount:1, _todo:'next_card_modifier'}]},
  {id:'sk_militia_soul_gain', name:'영혼 획득', element:'earth', role:'support', rarity:'bronze', kind:'spell-aoe', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:0, keywords:[], ability:'즉시 영혼 풀 +1 / 매 턴 영혼 획득 + 1', desc:'', bundledByUnit:'militia', unlockLevel:3, transferable:false, upgradeChoices:[], effects:[{op:'soul_gain', amount:1}]},
  {id:'sk_militia_cooking', name:'요리', element:'earth', role:'support', rarity:'bronze', kind:'spell-target', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:1, keywords:[], ability:'아군 1체 HP +1', desc:'', bundledByUnit:'militia', unlockLevel:4, transferable:false, upgradeChoices:[], effects:[{op:'heal', target:'ally_one', amount:1}]},

  // 궁병 (archer) — 5
  {id:'sk_archer_basic_attack', name:'활쏘기', element:'lightning', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해', desc:'', bundledByUnit:'archer', unlockLevel:1, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_archer_basic_attack2', name:'정조준 사격', element:'lightning', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해', desc:'', bundledByUnit:'archer', unlockLevel:2, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_archer_fire_arrow', name:'불화살', element:'fire', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체 1 피해 + 1턴 화상', desc:'', bundledByUnit:'archer', unlockLevel:3, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1},{op:'burn', target:'enemy_one', turns:1}]},
  {id:'sk_archer_focus_fire', name:'집중 사격', element:'lightning', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'지정 적 1체에 피해 2', desc:'', bundledByUnit:'archer', unlockLevel:4, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:2}]},
  {id:'sk_archer_squad_buff', name:'궁수 강화', element:'lightning', role:'support', rarity:'bronze', kind:'attach-hero', dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:1, HP:0, keywords:[], ability:'모든 궁수 ATK +1 (지속)', desc:'', bundledByUnit:'archer', unlockLevel:5, transferable:false, upgradeChoices:[], effects:[{op:'aura', filter:{type:'id_contains', value:'archer'}, stat:'ATK', amount:1}]},

  // 창병 (lancer) — 4
  {id:'sk_lancer_thrust', name:'찌르기 공격', element:'lightning', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'melee', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해', desc:'', bundledByUnit:'lancer', unlockLevel:1, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_lancer_anti_cavalry', name:'기병 격파', element:'lightning', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'melee', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적에게 피해 + 1 줍니다(기병일경우에는 2배의 피해를 입힙니다)', desc:'', bundledByUnit:'lancer', unlockLevel:2, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:4, condition:{type:'id_contains', value:'cavalry'}}]},
  {id:'sk_lancer_shield_block', name:'창병 방패 막기', element:'lightning', role:'defense', rarity:'bronze', kind:'attach-unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:0, DEF:2, defTurns:1, keywords:[], ability:'자신에게 보호막 +2 (1턴)', desc:'', bundledByUnit:'lancer', unlockLevel:3, transferable:false, upgradeChoices:[], effects:[{op:'shield', target:'self', amount:2, turns:1}]},
  {id:'sk_lancer_javelin', name:'투창 던지기', element:'lightning', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'수호병을 무시한 적 1체에게 1 피해', desc:'', bundledByUnit:'lancer', unlockLevel:4, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:3}]},

  // 수비병 (guard) — 4
  {id:'sk_guard_thrust', name:'수비병 찌르기', element:'water', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'melee', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해', desc:'', bundledByUnit:'guard', unlockLevel:1, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:2}]},
  {id:'sk_guard_shield', name:'방패 자세', element:'water', role:'defense', rarity:'bronze', kind:'attach-unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:0, DEF:2, defTurns:1, keywords:['taunt'], ability:'자신에게 보호막 +2 + 수호자 (1턴)', desc:'', bundledByUnit:'guard', unlockLevel:2, transferable:false, upgradeChoices:[], effects:[{op:'shield', target:'self', amount:2, turns:1, addKeyword:'taunt'}]},
  {id:'sk_guard_pierce_javelin', name:'창 던지기 (관통)', element:'water', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'지정한 적 피해 + 1 (수호자 무시)', desc:'', bundledByUnit:'guard', unlockLevel:3, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:4, pierce:'shield'}]},
  {id:'sk_guard_reorganize', name:'수비병 재정비', element:'water', role:'support', rarity:'bronze', kind:'attach-unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:1, keywords:[], ability:'자신 HP + 1', desc:'', bundledByUnit:'guard', unlockLevel:4, transferable:false, upgradeChoices:[], effects:[{op:'attach_buff', target:'self', stat:'HP', amount:1}]},

  // 불꽃정령 (fire_spirit) — 4
  {id:'sk_firespirit_fireball', name:'화염구 (정령)', element:'fire', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'magic', magicKind:'debuff', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해 (불)', desc:'', bundledByUnit:'fire_spirit', unlockLevel:1, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_firespirit_enchant', name:'불꽃 인챈트', element:'fire', role:'support', rarity:'bronze', kind:'attach-unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'아군 1체 1턴간 ATK +1', desc:'', bundledByUnit:'fire_spirit', unlockLevel:2, transferable:false, upgradeChoices:[], effects:[{op:'attach_buff', target:'ally_one', stat:'ATK', amount:1, turns:1}]},
  {id:'sk_firespirit_giant', name:'거대화', element:'fire', role:'attack', rarity:'bronze', kind:'attach-unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:1, HP:1, keywords:[], ability:'자신 1턴간 ATK +2 / HP +2', desc:'', bundledByUnit:'fire_spirit', unlockLevel:3, transferable:false, upgradeChoices:[], effects:[{op:'attach_buff', target:'self', stat:'ATK', amount:2, turns:1},{op:'attach_buff', target:'self', stat:'HP', amount:2, turns:1}]},
  {id:'sk_firespirit_self_destruct', name:'자폭', element:'fire', role:'attack', rarity:'bronze', kind:'spell-aoe', dmgType:'magic', magicKind:'debuff', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'지정한 적 + 양 옆 한 칸씩 (최대 3명) 각 피해 1. 불꽃정령은 사라집니다.', desc:'', bundledByUnit:'fire_spirit', unlockLevel:4, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1},{op:'damage', target:'enemy_adjacent', amount:1},{op:'self_destruct'}]},

  // 견습마법사 (apprentice) — 5
  {id:'sk_apprentice_fire_attack', name:'화염 공격', element:'fire', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'magic', magicKind:'debuff', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해 (불)', desc:'', bundledByUnit:'apprentice', unlockLevel:1, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:3}]},
  {id:'sk_apprentice_fireball', name:'화염구 (시그니처)', element:'fire', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'magic', magicKind:'debuff', NEED_SOUL:2, ATK:2, HP:0, keywords:[], ability:'적 1체에게 2  피해 (시그니처)', desc:'', bundledByUnit:'apprentice', unlockLevel:2, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:5}]},
  {id:'sk_apprentice_focus', name:'마법 집중', element:'fire', role:'support', rarity:'bronze', kind:'attach-hero', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:0, keywords:[], ability:'다음 스펠 NEED_SOUL -1', desc:'', bundledByUnit:'apprentice', unlockLevel:3, transferable:false, upgradeChoices:[], effects:[{op:'next_card_discount', amount:1, filter:{type:'kind_prefix', value:'spell'}, _todo:'filtered_next_card_modifier'}]},
  {id:'sk_apprentice_fire_focus', name:'화염 집중', element:'fire', role:'support', rarity:'bronze', kind:'attach-hero', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:0, keywords:[], ability:'본인이 사용할 모든 불 공격 피해 +1 (1턴간)', desc:'', bundledByUnit:'apprentice', unlockLevel:4, transferable:false, upgradeChoices:[], effects:[{op:'next_card_damage_buff', amount:2, filter:{type:'element_kind', element:'fire', kindPrefix:'spell'}, _todo:'element_filtered_dmg_buff'}]},
  {id:'sk_apprentice_fire_shield', name:'화염 방패', element:'fire', role:'defense', rarity:'bronze', kind:'attach-unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:0, DEF:1, defTurns:1, reflectAmt:1, reflectTurns:1, keywords:[], ability:'자신에게 보호막 +1 + 반사 1 (1턴)', desc:'', bundledByUnit:'apprentice', unlockLevel:5, transferable:false, upgradeChoices:[], effects:[{op:'shield', target:'self', amount:1, turns:1, reflect:1}]},

  // 석궁병 (crossbow) — 7
  {id:'sk_crossbow_basic_attack', name:'석궁 일반 공격', element:'fire', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해', desc:'', bundledByUnit:'crossbow', unlockLevel:1, transferable:true, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_crossbow_rapid_fire', name:'연속 공격', element:'fire', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:2, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해 (2발)', desc:'', bundledByUnit:'crossbow', unlockLevel:2, transferable:true, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:2, hits:2}]},
  {id:'sk_crossbow_double_shot', name:'연손 공격', element:'fire', role:'attack', rarity:'bronze', kind:'spell-aoe', dmgType:'ranged', NEED_SOUL:2, ATK:2, HP:0, keywords:[], ability:'적 1체에게 피해 +1 (2번 공격)', desc:'', bundledByUnit:'crossbow', unlockLevel:3, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_n', amount:2, count:2}]},
  {id:'sk_crossbow_stealth', name:'은폐 (시그니처)', element:'fire', role:'defense', rarity:'bronze', kind:'attach-unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:0, keywords:[], ability:'자신 다음 1회 회피', desc:'', bundledByUnit:'crossbow', unlockLevel:4, transferable:false, upgradeChoices:[], effects:[{op:'stealth', target:'self', turns:1}]},
  {id:'sk_crossbow_focus', name:'사격 집중 (시그니처)', element:'fire', role:'support', rarity:'bronze', kind:'attach-hero', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:0, keywords:[], ability:'다음 1번 스킬/공격 데미지 + 1 ', desc:'', bundledByUnit:'crossbow', unlockLevel:6, transferable:false, upgradeChoices:[], effects:[{op:'next_card_damage_buff', amount:2, filter:{type:'id_contains', value:'shot|fire|arrow|crossbow'}, _todo:'shot_filter'}]},
  {id:'sk_crossbow_bomb_arrow', name:'폭탄 화살', element:'fire', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:2, ATK:1, HP:0, keywords:[], ability:'적 1체 1 피해 + 인접 적 (최대2명) 1 피해', desc:'', bundledByUnit:'crossbow', unlockLevel:5, transferable:true, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:4},{op:'damage', target:'enemy_adjacent', amount:2}]},
  {id:'sk_crossbow_rest', name:'휴식 (시그니처)', element:'fire', role:'support', rarity:'bronze', kind:'attach-unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:1, keywords:[], ability:'자신 HP +1', desc:'', bundledByUnit:'crossbow', unlockLevel:7, transferable:false, upgradeChoices:[], effects:[{op:'heal', target:'self', amount:1}]},

  // ─────────── 도적 (rogue) — 2026-05-06 신규 3종 ───────────
  {id:'sk_rogue_basic_attack', name:'기습 일격', element:'dark', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'melee', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해', desc:'', bundledByUnit:'rogue', unlockLevel:1, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_rogue_assassinate', name:'암살 공격', element:'dark', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해 (지원/원거리 대상은 2 피해)', desc:'', bundledByUnit:'rogue', unlockLevel:2, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:2, condition:{type:'role_in', value:'support|ranged'}, _todo:'role_double_dmg'}]},
  {id:'sk_rogue_steal', name:'카드 훔치기', element:'dark', role:'support', rarity:'bronze', kind:'spell-target', dmgType:'magic', magicKind:'debuff', NEED_SOUL:1, ATK:0, HP:0, keywords:[], ability:'적 손패 1장 훔쳐 자신 손패에 추가 (사용 시 소멸)', desc:'', bundledByUnit:'rogue', unlockLevel:3, transferable:true, upgradeChoices:[], effects:[{op:'_todo', _todo:'steal_random_hand_card', _redesign:'enemy_hand_random'}]},

  // ─────────── 원숭이 (monkey, bronze) — 2026-05-06 신규 2종 ───────────
  {id:'sk_monkey_scratch', name:'할퀴기', element:'earth', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'melee', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해', desc:'', bundledByUnit:'monkey', unlockLevel:1, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_monkey_stone_throw', name:'돌 던지기', element:'earth', role:'attack', rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'원거리 적 1체에게 1 피해', desc:'', bundledByUnit:'monkey', unlockLevel:2, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},

  // ─────────── 원숭이장군 (monkey_general, silver) — 2026-05-06 신규 3종 ───────────
  {id:'sk_general_thrust', name:'장군 찌르기', element:'earth', role:'attack', rarity:'silver', kind:'spell-target', dmgType:'melee', NEED_SOUL:2, ATK:2, HP:0, keywords:[], ability:'적 1체에게 2 피해', desc:'', bundledByUnit:'monkey_general', unlockLevel:1, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:2}]},
  {id:'sk_general_defend', name:'방어 자세', element:'earth', role:'defense', rarity:'silver', kind:'attach-unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:0, HP:0, DEF:2, defTurns:2, keywords:[], ability:'자신에게 보호막 +2 (1턴)', desc:'', bundledByUnit:'monkey_general', unlockLevel:2, transferable:false, upgradeChoices:[], effects:[{op:'shield', target:'self', amount:2, turns:1}]},
  {id:'sk_general_meditation', name:'명상하기', element:'earth', role:'support', rarity:'silver', kind:'attach-unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:1, HP:1, keywords:[], ability:'자신 ATK +1, HP +1', desc:'', bundledByUnit:'monkey_general', unlockLevel:3, transferable:false, upgradeChoices:[], effects:[{op:'attach_buff', target:'self', stat:'ATK', amount:1},{op:'attach_buff', target:'self', stat:'HP', amount:1}]},

  // ─────────── 오공 (wukong, gold) — 2026-05-06 신규 3종 ───────────
  {id:'sk_wukong_basic', name:'불타는 여의봉', element:'earth', role:'attack', rarity:'gold', kind:'spell-aoe', NEED_SOUL:3, ATK:0, HP:0, dmgType:'magic', magicKind:'buff', keywords:[], ability:'오공 공격력 +3 (이번 라운드)', desc:'', bundledByUnit:'wukong', unlockLevel:1, transferable:false, upgradeChoices:[], effects:[{op:'attach_buff', target:'self', stat:'ATK', amount:3, turns:1}]},
  {id:'sk_wukong_aoe', name:'봉의 광역', element:'earth', role:'attack', rarity:'gold', kind:'spell-target', dmgType:'melee', NEED_SOUL:3, ATK:3, HP:0, keywords:[], ability:'오공의 공격력 X 로 광역 공격 (지정한 적군 양 옆 피해입힘 , 최대 2명)', desc:'', bundledByUnit:'wukong', unlockLevel:2, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:3},{op:'damage', target:'enemy_adjacent', amount:3}]},
  {id:'sk_wukong_clone', name:'분신술 (오공)', element:'earth', role:'support', rarity:'gold', kind:'spell-aoe', dmgType:'magic', magicKind:'buff', NEED_SOUL:3, ATK:0, HP:0, keywords:[], ability:'본인 분신 1마리 보드 소환 (HP 1, ATK X (현재 본인 카드), 한대 맞으면 소멸)', desc:'', bundledByUnit:'wukong', unlockLevel:3, transferable:false, upgradeChoices:[], effects:[{op:'summon', stats:{HP:1, ATK:1}, name:'monkey_clone'}]},

  // ─────────── 손오공 (sun_wukong, legendary) — 2026-05-06 신규 3종 ───────────
  {id:'sk_sun_wukong_basic', name:'천축의 봉', element:'earth', role:'attack', rarity:'legendary', kind:'spell-target', dmgType:'melee', NEED_SOUL:5, ATK:6, HP:0, keywords:[], ability:'적 1체에게 6 피해', desc:'', bundledByUnit:'sun_wukong', unlockLevel:1, transferable:false, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:6}]},
  {id:'sk_sun_wukong_revive', name:'근두운 부활', element:'earth', role:'support', rarity:'legendary', kind:'attach-unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:5, ATK:0, HP:0, keywords:[], ability:'자신 사망 시 1회 부활 (HP 50%) 소멸카드(1번만사용가능)', desc:'', bundledByUnit:'sun_wukong', unlockLevel:2, transferable:false, upgradeChoices:[], effects:[{op:'_todo', _todo:'one_time_revive_50pct', _redesign:'revive_consume'}]},
  {id:'sk_sun_wukong_clone', name:'분신술 (손오공)', element:'earth', role:'support', rarity:'legendary', kind:'spell-aoe', dmgType:'magic', magicKind:'buff', NEED_SOUL:5, ATK:0, HP:0, keywords:[], ability:'분신 1마리 보드 소환 (HP 1, ATK 손오공과 동일)', desc:'', bundledByUnit:'sun_wukong', unlockLevel:3, transferable:false, upgradeChoices:[], effects:[{op:'summon', stats:{HP:1, ATK:6}, name:'sun_wukong_clone', _todo:'mirror_caster_atk'}]},

  // ─────────── 화염술사 (pyromancer, silver) — 2026-05-09 신규 5종 ───────────
  {id:'sk_pyromancer_fireball', name:'화염구', element:'fire', role:'attack', rarity:'silver', kind:'spell-target', dmgType:'magic', magicKind:'debuff', NEED_SOUL:2, ATK:2, HP:0, keywords:[], ability:'적 1체에게 2 피해', desc:'', bundledByUnit:'pyromancer', unlockLevel:1, transferable:true, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:2}]},
  {id:'sk_pyromancer_burning_orb', name:'업화구', element:'fire', role:'attack', rarity:'silver', kind:'spell-target', dmgType:'magic', magicKind:'debuff', NEED_SOUL:3, ATK:3, HP:0, keywords:[], ability:'적 1체 3 피해 + 인접 1칸씩 1 추가 피해', desc:'', bundledByUnit:'pyromancer', unlockLevel:4, transferable:true, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:3},{op:'damage', target:'enemy_adjacent', amount:1}]},
  {id:'sk_pyromancer_soul_drain', name:'영혼 흡수', element:'fire', role:'support', rarity:'silver', kind:'spell-target', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:0, keywords:[], ability:'지정한 아군의 남은 모든 체력을 영혼력으로 치환합니다', desc:'', bundledByUnit:'pyromancer', unlockLevel:5, transferable:true, upgradeChoices:[], effects:[{op:'_todo', _todo:'convert_ally_hp_to_soul', _redesign:'sacrifice_ally_for_soul'}]},
  {id:'sk_pyromancer_learn', name:'학습', element:'fire', role:'support', rarity:'silver', kind:'spell-target', dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:0, HP:0, keywords:[], ability:'지정한 아군의 경험치 +2 (적군은 대상 X)', desc:'', bundledByUnit:'pyromancer', unlockLevel:3, transferable:false, upgradeChoices:[], effects:[{op:'_todo', _todo:'grant_ally_exp_2', _redesign:'ally_exp_buff'}]},
  {id:'sk_pyromancer_ignite', name:'발화', element:'fire', role:'attack', rarity:'silver', kind:'attach-hero', dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:0, HP:0, keywords:[], ability:'다음 턴에 사용하는 모든 화염 스펠이 한 단계 업그레이드됩니다', desc:'', bundledByUnit:'pyromancer', unlockLevel:10, transferable:false, upgradeChoices:[], effects:[{op:'_todo', _todo:'upgrade_fire_spells_next_turn', _redesign:'fire_spell_tier_buff'}]},
  {id:'sk_pyromancer_flame_imbue', name:'화염 각인', element:'fire', role:'support', rarity:'silver', kind:'attach-unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:0, keywords:[], ability:'지정 아군 유닛 다음 공격 1회: ATK +1 + 화상 1 (1턴)', desc:'불의 인장을 새겨 다음 일격에 불꽃을 싣는다.', bundledByUnit:'pyromancer', upgradeChoices:[], effects:[{op:'_todo', _todo:'flame_imbue', atkBonus:1, burnAmount:1, turns:1}]},
  {id:'sk_pyromancer_flame_shield', name:'화염방패', element:'fire', role:'defense', rarity:'silver', kind:'attach-unit', dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:0, HP:0, DEF:1, defTurns:1, reflectBurnAmt:1, reflectBurnTurns:1, unlockLevel:2, transferable:false, selfOnly:false, keywords:[], ability:'지정 아군 1체 DEF +1 보호막 (1턴), 피격 시 근접 공격자에게 화상 1 (1턴)', desc:'불의 외투가 창끝을 마중한다.', bundledByUnit:'pyromancer', upgradeChoices:[], effects:[{op:'shield', target:'self', amount:1, turns:1}]},

  // ─────────── 영웅 시그니처 — 2026-05-09 신규 30종 (6 영웅 × 5 레벨 스킬) ───────────
  // bundledByUnit 매핑: 'hero_m_warrior_holy' / 'hero_m_ranger_holy' / ... (createHero 결과 id 매칭)

  // 남주인공 근접 (m.warrior, holy) ─────
  {id:'sk_hero_m_warrior_attack',    name:'공격하기',      element:'holy', role:'attack',  rarity:'bronze', kind:'spell-target', dmgType:'melee', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해', desc:'', bundledByUnit:'hero_m_warrior_holy', unlockLevel:1, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_hero_m_warrior_shield',    name:'방패막기',      element:'holy', role:'defense', rarity:'bronze', kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:0, HP:0, DEF:2, defTurns:2, keywords:[], ability:'영웅 DEF +2 (2턴)', desc:'', bundledByUnit:'hero_m_warrior_holy', unlockLevel:2, upgradeChoices:[], effects:[{op:'shield', target:'hero', amount:2, turns:2}]},
  {id:'sk_hero_m_warrior_train',     name:'훈련',          element:'holy', role:'support', rarity:'bronze', kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:1, HP:0, keywords:[], ability:'ATK +1 + 다음 턴 카드 1장 추가 드로우', desc:'', bundledByUnit:'hero_m_warrior_holy', unlockLevel:3, upgradeChoices:[], effects:[{op:'attach_buff', target:'hero', stat:'ATK', amount:1},{op:'_todo', _todo:'next_turn_extra_draw_1'}]},
  {id:'sk_hero_m_warrior_morale',    name:'사기',          element:'holy', role:'support', rarity:'bronze',   kind:'spell-aoe',    dmgType:'magic', magicKind:'buff', NEED_SOUL:3, ATK:1, HP:1, keywords:[], ability:'보드 위 모든 아군 ATK +1, HP +1', desc:'', bundledByUnit:'hero_m_warrior_holy', unlockLevel:4, upgradeChoices:[], effects:[{op:'attach_buff', target:'ally_all', stat:'ATK', amount:1},{op:'attach_buff', target:'ally_all', stat:'HP', amount:1}]},
  {id:'sk_hero_m_warrior_soul_boost',name:'영혼력 증가',   element:'holy', role:'support', rarity:'bronze',   kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:0, HP:0, keywords:[], ability:'다음 턴부터 영혼력 +1 (지속)', desc:'', bundledByUnit:'hero_m_warrior_holy', unlockLevel:5, upgradeChoices:[], effects:[{op:'soul_gain', amount:1, _todo:'persistent_soul_boost'}]},

  // 남주인공 마법 (m.support, holy) ─────
  {id:'sk_hero_m_support_attack',    name:'신성 공격',     element:'holy', role:'attack',  rarity:'bronze', kind:'spell-target', dmgType:'magic', magicKind:'debuff', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해', desc:'', bundledByUnit:'hero_m_support_holy', unlockLevel:1, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_hero_m_support_heal',      name:'치유',          element:'holy', role:'support', rarity:'bronze', kind:'spell-target', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:1, keywords:[], ability:'아군 1체 HP +1', desc:'', bundledByUnit:'hero_m_support_holy', unlockLevel:2, upgradeChoices:[], effects:[{op:'heal', target:'ally_one', amount:1}]},
  {id:'sk_hero_m_support_teach',     name:'마법 교육',     element:'holy', role:'support', rarity:'bronze', kind:'spell-target', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:0, keywords:[], ability:'아군 1체 경험치 +1', desc:'', bundledByUnit:'hero_m_support_holy', unlockLevel:3, upgradeChoices:[], effects:[{op:'_todo', _todo:'grant_ally_exp_1'}]},
  {id:'sk_hero_m_support_divine_army',name:'신의 군대',    element:'holy', role:'support', rarity:'bronze',   kind:'spell-aoe',    dmgType:'magic', magicKind:'buff', NEED_SOUL:3, ATK:1, HP:1, keywords:[], ability:'보드 위 모든 아군 ATK +1, HP +1', desc:'', bundledByUnit:'hero_m_support_holy', unlockLevel:4, upgradeChoices:[], effects:[{op:'attach_buff', target:'ally_all', stat:'ATK', amount:1},{op:'attach_buff', target:'ally_all', stat:'HP', amount:1}]},
  {id:'sk_hero_m_support_soul_boost',name:'영혼력 증가',   element:'holy', role:'support', rarity:'bronze',   kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:0, HP:0, keywords:[], ability:'다음 턴부터 영혼력 +1 (지속)', desc:'', bundledByUnit:'hero_m_support_holy', unlockLevel:5, upgradeChoices:[], effects:[{op:'soul_gain', amount:1, _todo:'persistent_soul_boost'}]},

  // 남주인공 원거리 (m.ranger, holy) ─────
  {id:'sk_hero_m_ranger_attack',     name:'원거리 공격',   element:'holy', role:'attack',  rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해', desc:'', bundledByUnit:'hero_m_ranger_holy', unlockLevel:1, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_hero_m_ranger_volley',     name:'원거리 연속공격',element:'holy',role:'attack',  rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체 1 피해 + 인접 1칸 1 피해', desc:'', bundledByUnit:'hero_m_ranger_holy', unlockLevel:2, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1},{op:'damage', target:'enemy_adjacent', amount:1}]},
  {id:'sk_hero_m_ranger_hunt',       name:'사슴 사냥',     element:'holy', role:'support', rarity:'bronze', kind:'spell-aoe',    dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:1, keywords:[], ability:'전체 아군 HP +1', desc:'', bundledByUnit:'hero_m_ranger_holy', unlockLevel:3, upgradeChoices:[], effects:[{op:'heal', target:'ally_all', amount:1}]},
  {id:'sk_hero_m_ranger_archery',    name:'궁술 지도',     element:'holy', role:'attack',  rarity:'bronze',   kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:0, HP:0, keywords:[], ability:'모든 원거리 피해 +1 (지속)', desc:'', bundledByUnit:'hero_m_ranger_holy', unlockLevel:4, upgradeChoices:[], effects:[{op:'aura', filter:{type:'role_eq', value:'ranged'}, stat:'ATK', amount:1, _todo:'ranged_dmg_aura'}]},
  {id:'sk_hero_m_ranger_soul_boost', name:'영혼력 증가',   element:'holy', role:'support', rarity:'bronze',   kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:0, HP:0, keywords:[], ability:'다음 턴부터 영혼력 +1 (지속)', desc:'', bundledByUnit:'hero_m_ranger_holy', unlockLevel:5, upgradeChoices:[], effects:[{op:'soul_gain', amount:1, _todo:'persistent_soul_boost'}]},

  // 여주인공 근접 (f.warrior, holy) ─────
  {id:'sk_hero_f_warrior_attack',    name:'공격하기',      element:'holy', role:'attack',  rarity:'bronze', kind:'spell-target', dmgType:'melee', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해', desc:'', bundledByUnit:'hero_f_warrior_holy', unlockLevel:1, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_hero_f_warrior_shield',    name:'방패막기',      element:'holy', role:'defense', rarity:'bronze', kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:0, HP:0, DEF:2, defTurns:2, keywords:[], ability:'영웅 DEF +2 (2턴)', desc:'', bundledByUnit:'hero_f_warrior_holy', unlockLevel:2, upgradeChoices:[], effects:[{op:'shield', target:'hero', amount:2, turns:2}]},
  {id:'sk_hero_f_warrior_train',     name:'훈련',          element:'holy', role:'support', rarity:'bronze', kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:1, HP:0, keywords:[], ability:'ATK +1 + 다음 턴 카드 1장 추가 드로우', desc:'', bundledByUnit:'hero_f_warrior_holy', unlockLevel:3, upgradeChoices:[], effects:[{op:'attach_buff', target:'hero', stat:'ATK', amount:1},{op:'_todo', _todo:'next_turn_extra_draw_1'}]},
  {id:'sk_hero_f_warrior_morale',    name:'사기',          element:'holy', role:'support', rarity:'bronze',   kind:'spell-aoe',    dmgType:'magic', magicKind:'buff', NEED_SOUL:3, ATK:1, HP:1, keywords:[], ability:'보드 위 모든 아군 ATK +1, HP +1', desc:'', bundledByUnit:'hero_f_warrior_holy', unlockLevel:4, upgradeChoices:[], effects:[{op:'attach_buff', target:'ally_all', stat:'ATK', amount:1},{op:'attach_buff', target:'ally_all', stat:'HP', amount:1}]},
  {id:'sk_hero_f_warrior_soul_boost',name:'영혼력 증가',   element:'holy', role:'support', rarity:'bronze',   kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:0, HP:0, keywords:[], ability:'다음 턴부터 영혼력 +1 (지속)', desc:'', bundledByUnit:'hero_f_warrior_holy', unlockLevel:5, upgradeChoices:[], effects:[{op:'soul_gain', amount:1, _todo:'persistent_soul_boost'}]},

  // 여주인공 마법 (f.support, holy) ─────
  {id:'sk_hero_f_support_attack',    name:'신성 공격',     element:'holy', role:'attack',  rarity:'bronze', kind:'spell-target', dmgType:'magic', magicKind:'debuff', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해', desc:'', bundledByUnit:'hero_f_support_holy', unlockLevel:1, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_hero_f_support_heal',      name:'치유',          element:'holy', role:'support', rarity:'bronze', kind:'spell-target', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:1, keywords:[], ability:'아군 1체 HP +1', desc:'', bundledByUnit:'hero_f_support_holy', unlockLevel:2, upgradeChoices:[], effects:[{op:'heal', target:'ally_one', amount:1}]},
  {id:'sk_hero_f_support_teach',     name:'마법 교육',     element:'holy', role:'support', rarity:'bronze', kind:'spell-target', dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:0, keywords:[], ability:'아군 1체 경험치 +1', desc:'', bundledByUnit:'hero_f_support_holy', unlockLevel:3, upgradeChoices:[], effects:[{op:'_todo', _todo:'grant_ally_exp_1'}]},
  {id:'sk_hero_f_support_divine_army',name:'신의 군대',    element:'holy', role:'support', rarity:'bronze',   kind:'spell-aoe',    dmgType:'magic', magicKind:'buff', NEED_SOUL:3, ATK:1, HP:1, keywords:[], ability:'보드 위 모든 아군 ATK +1, HP +1', desc:'', bundledByUnit:'hero_f_support_holy', unlockLevel:4, upgradeChoices:[], effects:[{op:'attach_buff', target:'ally_all', stat:'ATK', amount:1},{op:'attach_buff', target:'ally_all', stat:'HP', amount:1}]},
  {id:'sk_hero_f_support_soul_boost',name:'영혼력 증가',   element:'holy', role:'support', rarity:'bronze',   kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:0, HP:0, keywords:[], ability:'다음 턴부터 영혼력 +1 (지속)', desc:'', bundledByUnit:'hero_f_support_holy', unlockLevel:5, upgradeChoices:[], effects:[{op:'soul_gain', amount:1, _todo:'persistent_soul_boost'}]},

  // 여주인공 원거리 (f.ranger, holy) ─────
  {id:'sk_hero_f_ranger_attack',     name:'원거리 공격',   element:'holy', role:'attack',  rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체에게 1 피해', desc:'', bundledByUnit:'hero_f_ranger_holy', unlockLevel:1, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1}]},
  {id:'sk_hero_f_ranger_volley',     name:'원거리 연속공격',element:'holy',role:'attack',  rarity:'bronze', kind:'spell-target', dmgType:'ranged', NEED_SOUL:1, ATK:1, HP:0, keywords:[], ability:'적 1체 1 피해 + 인접 1칸 1 피해', desc:'', bundledByUnit:'hero_f_ranger_holy', unlockLevel:2, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:1},{op:'damage', target:'enemy_adjacent', amount:1}]},
  {id:'sk_hero_f_ranger_hunt',       name:'사슴 사냥',     element:'holy', role:'support', rarity:'bronze', kind:'spell-aoe',    dmgType:'magic', magicKind:'buff', NEED_SOUL:1, ATK:0, HP:1, keywords:[], ability:'전체 아군 HP +1', desc:'', bundledByUnit:'hero_f_ranger_holy', unlockLevel:3, upgradeChoices:[], effects:[{op:'heal', target:'ally_all', amount:1}]},
  {id:'sk_hero_f_ranger_archery',    name:'궁술 지도',     element:'holy', role:'attack',  rarity:'bronze',   kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:0, HP:0, keywords:[], ability:'모든 원거리 피해 +1 (지속)', desc:'', bundledByUnit:'hero_f_ranger_holy', unlockLevel:4, upgradeChoices:[], effects:[{op:'aura', filter:{type:'role_eq', value:'ranged'}, stat:'ATK', amount:1, _todo:'ranged_dmg_aura'}]},
  {id:'sk_hero_f_ranger_soul_boost', name:'영혼력 증가',   element:'holy', role:'support', rarity:'bronze',   kind:'attach-hero',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:0, HP:0, keywords:[], ability:'다음 턴부터 영혼력 +1 (지속)', desc:'', bundledByUnit:'hero_f_ranger_holy', unlockLevel:5, upgradeChoices:[], effects:[{op:'soul_gain', amount:1, _todo:'persistent_soul_boost'}]},

  // ─────────── 신화급 스펠 — 염룡술 (2026-05-17 이펙트 검증용) ───────────
  // 2026-06-15 사용자 결정: 보존카드 시스템에서 해제 — _persistent 플래그 삭제로 AI·플레이어 누구도 강제 보유 X.
  //   (옛 _persistent:true = 매치 시작 시 모든 영웅 손패 강제 추가 + cleanup 제외 임시 테스트. project_temp_dragon_flame_all_heroes.md)
  //   현재 어떤 덱/번들/시그니처/봇에도 미배포 = dormant. 데이터·이펙트(_animDragonFlame)·이미지는 정식 divine 룰 확정 대비 보존.
  //   엔진의 보존(retain→_persistent) 메커니즘 자체는 범용으로 유지 (match-lifecycle-retain-v6 가 별도 카드로 검증).
  {id:'sk_dragon_flame', name:'염룡술', element:'fire', role:'attack', rarity:'divine', kind:'spell-aoe', dmgType:'magic', magicKind:'debuff', NEED_SOUL:5, ATK:1, HP:0, keywords:[], ability:'모든 적군 화염 피해 1 + 화상 2 (2턴)', desc:'하늘에서 강림한 염룡이 모든 적군을 화염으로 태운다.', upgradeChoices:[], effects:[{op:'damage', target:'enemy_all_incl_hero', amount:1},{op:'burn', target:'enemy_all_incl_hero', amount:2, turns:2}]},

  // ─────────── 우두머리 늑대 (hero_wolf_alpha) 시그니처 5장 — q_wolf_cull (design/quest_lines_v1.md v3) ───────────
  // 첫 named-hero 의 시그니처 풀. unlockLevel 1~5. 전부 고유(transferable:false, 우두머리 캐릭터 등장).
  // alpha_call: SoT 'spell-target' → 'spell-aoe' 보정 (spell-target 은 적 타겟 없으면 effect 미적용. 소환은 self-board → spell-aoe).
  {id:'sk_wolf_alpha_scratch',      name:'할퀴기',          element:'earth', role:'attack',  rarity:'silver', kind:'spell-target', dmgType:'melee', NEED_SOUL:2, ATK:2, HP:0, keywords:[], ability:'적 1체에 2 피해', desc:'', bundledByUnit:'hero_wolf_alpha', transferable:false, unlockLevel:1, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:2}]},
  {id:'sk_wolf_alpha_bite',         name:'물기',            element:'earth', role:'attack',  rarity:'silver', kind:'spell-target', dmgType:'melee', NEED_SOUL:2, ATK:2, HP:0, keywords:[], ability:'적 1체에 2 피해', desc:'', bundledByUnit:'hero_wolf_alpha', transferable:false, unlockLevel:2, upgradeChoices:[], effects:[{op:'damage', target:'enemy_one', amount:2}]},
  {id:'sk_wolf_alpha_agile',        name:'민첩함',          element:'earth', role:'support', rarity:'silver', kind:'attach-self',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:0, HP:0, keywords:[], ability:'[스펠주인]에게 다음 1회 공격 회피 부여', desc:'', bundledByUnit:'hero_wolf_alpha', transferable:false, unlockLevel:3, upgradeChoices:[], effects:[{op:'_todo', _todo:'evade_once'}]},
  {id:'sk_wolf_alpha_natural_gift', name:'자연의 선물',     element:'earth', role:'support', rarity:'silver', kind:'attach-self',  dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:0, HP:2, keywords:[], ability:'[스펠주인] 체력 2 회복', desc:'', bundledByUnit:'hero_wolf_alpha', transferable:false, unlockLevel:4, upgradeChoices:[], effects:[{op:'heal', target:'self', amount:2}]},
  {id:'sk_wolf_alpha_alpha_call',   name:'우두머리의 부름', element:'earth', role:'support', rarity:'silver', kind:'spell-aoe',    dmgType:'magic', magicKind:'buff', NEED_SOUL:2, ATK:0, HP:0, keywords:[], ability:'그림자에서 늑대 1마리 소환 (보드 자리 있을 때)', desc:'', bundledByUnit:'hero_wolf_alpha', transferable:false, unlockLevel:5, upgradeChoices:[], effects:[{op:'summon', summonId:'wolf', amount:1, boardCap:5}]},
]);

// 호환성 레이어
window.SKILLS_DB = RoF.Data.SKILLS;

// ─────────────────────────────────────────────────────────────
// 판별 헬퍼 (PHASE 6 — kind 기반)
// ─────────────────────────────────────────────────────────────
// passive 필드 폐기. 대신 kind 5종으로 분류:
//   'unit'         → 보드 소환 (passive 아님)
//   'spell-target' → 즉발 (passive 아님)
//   'spell-aoe'    → 즉발 (passive 아님)
//   'attach-hero'  → 영웅 부착 지속 효과 (passive)
//   'attach-unit'  → 유닛 부착 지속 효과 (passive)
RoF.isSkillPassive = function(idOrObj){
  let sk = idOrObj;
  if(typeof idOrObj === 'string'){
    sk = RoF.Data.SKILLS.find(s => s.id === idOrObj);
    if(!sk) return true; // 알 수 없는 id → 패시브로 처리해 회색 노출
  }
  return sk.kind === 'attach-hero' || sk.kind === 'attach-unit';
};

// ─────────────────────────────────────────────────────────────
// v2 form swap wrap (2026-05-26 — meta_progression_spec §3 정합)
//
// 옛 flat skill schema 를 nested v2 schema 로 wrap.
// 진화 후보 (evolveTo[]) 빈 배열 시작 — 102 강화 데이터 디자인 batch 후 채움.
// 옛 upgradeChoices 필드와 호환 — RoF.Meta.Upgrade.getChoices 는 옛 필드 사용 (v1 호환).
// ─────────────────────────────────────────────────────────────
RoF.Data.SKILL_DEF = (function(){
  const m = {};
  RoF.Data.SKILLS.forEach(sk => {
    m[sk.id] = {
      baseForm: sk.id,
      evolutions: {
        [sk.id]: {
          rarity: sk.rarity,
          name: sk.name,
          imgKey: sk.id,
          kind: sk.kind,
          element: sk.element || null,
          dmgType: sk.dmgType || null,
          effects: Array.isArray(sk.effects) ? sk.effects : [],
          stat: { NEED_SOUL: sk.NEED_SOUL, ATK: sk.ATK || 0, HP: sk.HP || 0, DEF: sk.DEF || 0 },
          evolveTo: [],     // 진화 후보 (별도 batch)
          unlock: null,
        },
      },
    };
  });
  return m;
})();
