// NOTE: This file must load before other 5x_game_*.js
RoF.Game = RoF.Game || {};

// Game Core (기본 속성 + core 메서드)
// Generated by docs/_split_game.py — Phase 4
// DO NOT hand-edit keys — edit in original and re-run splitter if needed.

RoF.__gameKeys = RoF.__gameKeys || new Set();
(function(keys){
  for (const k of keys) {
    if (RoF.__gameKeys.has(k)) {
      console.error('[Game] 중복 키 감지:', k);
      RoF.__gameKeyError = true;
    }
    RoF.__gameKeys.add(k);
  }
})(["round", "hp", "maxHp", "gold", "xp", "level", "honor", "deck", "relics", "maxDeck", "battleSpeed", "battleRunning", "skipReq", "_slowMo", "battleMultiplier", "load", "persist", "logout", "cardXpNext", "giveCardXp", "allocStatPoint", "giveCardHonor", "getHeroLevel", "getActionPoints", "getTotalHonor", "checkTutorial", "getProfileCard", "setProfileCard", "setProfileFrame", "getUnlockedCompanionCount", "COMPANION_UNLOCK"]);

Object.assign(RoF.Game, {
  round:0,hp:3,maxHp:3,gold:0,xp:0,level:1,honor:0,deck:[],relics:[],maxDeck:99,
  battleSpeed:500,battleRunning:false,skipReq:false,_slowMo:false,battleMultiplier:1,

  load(s){
    // 2026-05-10 v10: heroName 동기화 — Game.load 진입 시 Auth.heroName 도 함께 복원.
    // (login/signup 경로 외 dev navigator/Backend 경로에서도 일관성 보장)
    if(s && s.heroName && typeof Auth !== 'undefined') Auth.heroName = s.heroName;
    Object.assign(this,{round:s.round||0,hp:s.hp||3,maxHp:s.maxHp||3,gold:s.gold||2,
      deck:s.deck||[],relics:s.relics||[],ownedRelics:s.ownedRelics||[],ownedSkills:s.ownedSkills||[],hero:s.hero||null,bestRound:s.bestRound||0,totalWins:s.totalWins||0,totalGames:s.totalGames||0,leaguePoints:s.leaguePoints||0,tutStep:s.tutStep||0,companionName:s.companionName||'동료',blessings:s.blessings||0,winStreak:s.winStreak||0,tavernSlots:s.tavernSlots||null,tavernDate:s.tavernDate||null,
      profileCardId:s.profileCardId||null,
      profileFrameId:s.profileFrameId||'none',
      // 2026-05-26 v2: 운명의 인장 (각성/강화/회귀 공용 자원 — meta_progression_spec §6.6)
      awakeningSeal: s.awakeningSeal || 0,
      // 2026-05-31 퀘스트 v1 (design/quest_system_v1.md) — 도전 레벨 + 퀘 상태 + 카드 보유
      challengeLevel: s.challengeLevel || 1,
      challengeXP: s.challengeXP || 0,
      quests: s.quests || { active: [], completed: [], respawn: {}, lastDailyReset: 0 },
      ownedQuestCards: s.ownedQuestCards || []});
    // 2026-05-03: savedFormations FIFO 큐 → 고정 3슬롯 인덱스 (각 {name, units, relics}).
    // 사용자 결정 — 1·2·3번 슬롯 + 이름 편집 가능. 빈 슬롯은 units.length===0 으로 판정.
    const _sf = Array.isArray(s.savedFormations) ? s.savedFormations : [];
    this.savedFormations = [0, 1, 2].map(function(i){
      const f = _sf[i];
      return {
        name:   (f && typeof f.name === 'string' && f.name) ? f.name : ((i+1) + '번 편성'),
        units:  (f && Array.isArray(f.units))  ? f.units  : [],
        relics: (f && Array.isArray(f.relics)) ? f.relics : [],
      };
    });
    // PHASE 3 폐기 필드 (maxHp/shield/meva/hpReg/nrgReg/range/growthPts) populating 제거 (2026-05-16 P0 #5).
    // 옛 세이브 카드는 이미 박혀있으므로 호환층 (40_cards.js:608 fallback) 그대로 동작.
    // 새 카드는 PHASE 6 5필드 (HP/ATK/NEED_SOUL/SOUL/keywords) 만 보유.
    this.deck.forEach(c=>{
      if(!c.equips)c.equips=[];
      if(!c.xp)c.xp=0;
      if(!c.honor)c.honor=0;
      if(!c.level)c.level=1;
      if(c.freePoints==null)c.freePoints=0;
      // v1.1 mastery (2026-05-25 spec §11 영구 보관) — 옛 세이브 호환 default 주입.
      // 매치 종료 시 Match._commitMasteryToProfile 가 _permanentUid 매칭으로 swap.
      if(!c.skillMastery) c.skillMastery = {};
      // 2026-05-16 마이그레이션 — 옛 영입 카드의 ability/desc 를 정본 RoF.Data.UNITS / SKILLS 에서 fresh fetch
      // tavern 영입 시 spread 로 카드 복사 → 그 시점 ability/desc 박힘 → 정본 갱신 무시되는 문제 fix
      if(c.id && RoF.Data){
        const fresh = (RoF.Data.UNITS || []).find(u => u.id === c.id)
                   || (RoF.Data.SKILLS || []).find(s => s.id === c.id);
        if(fresh){
          c.ability = fresh.ability;
          c.desc = fresh.desc;
        }
      }
    });
    // 일회성 마이그레이션: 번개 타이탄 미보유 기존 세이브에 지급
    if(!this.deck.some(c=>c.id==='titan')){
      const tb=UNITS.find(x=>x.id==='titan');
      if(tb){
        // PHASE 3 폐기 필드 (maxHp/growthPts) 제거 (2026-05-16 P0 #5)
        this.deck.push({...tb,uid:uid(),isCompanion:true,isTitan:true,level:1,equips:[],xp:0,honor:0,freePoints:0});
      }
    }
    this.showMenu();
  },
  persist(){
    if(!Auth.user)return;const db=Auth.db();if(!db[Auth.user])return;
    // S4: league id 자동 계산 (채팅 RLS 가 save_data->>'league' 참조)
    const lg = this.getLeague ? this.getLeague() : null;
    const leagueId = (lg && lg.id) || 'bronze';
    const sv={round:this.round,hp:this.hp,maxHp:this.maxHp,gold:this.gold,gems:this.gems||0,blessings:this.blessings||0,divineGrace:this.divineGrace||0,
      deck:this.deck,relics:this.relics,ownedRelics:this.ownedRelics||[],ownedSkills:this.ownedSkills||[],hero:this.hero||null,bestRound:this.bestRound,totalWins:this.totalWins,totalGames:this.totalGames,leaguePoints:this.leaguePoints||0,league:leagueId,tutStep:this.tutStep||0,companionName:this.companionName||'동료',blessings:this.blessings||0,winStreak:this.winStreak||0,tavernSlots:this.tavernSlots||null,tavernDate:this.tavernDate||null,savedFormations:this.savedFormations||[],guild_id:this.guild_id||null,
      profileCardId:this.profileCardId||null,
      profileFrameId:this.profileFrameId||'none',
      awakeningSeal:this.awakeningSeal||0,
      challengeLevel:this.challengeLevel||1,
      challengeXP:this.challengeXP||0,
      quests:this.quests||{active:[],completed:[],respawn:{},lastDailyReset:0},
      ownedQuestCards:this.ownedQuestCards||[],
      heroName:(typeof Auth!=='undefined' && (Auth.heroName||Auth.user))||null};
    db[Auth.user].save=sv;
    Auth.save(db);
    // S1: 클라우드 세이브 (비동기, 실패해도 로컬은 이미 저장됨)
    if(Backend && Backend.isReady) Backend.saveProgress(sv).catch(()=>{});
  },
  async logout(){
    // 2026-04-24: 완전 로그아웃 — 저장 + Supabase 세션 종료 + auto-login 정보 + remember 플래그 제거.
    // async 화 이유: Supabase signOut 이 완료되기 전에 페이지가 멈추면 세션 토큰이 남아 재진입 시 자동 로그인.
    this.persist();
    Auth.user=null;
    this.battleRunning=false;
    SFX.bgm(false);
    // Auto-login / remember 플래그 정리 (다음 세션 자동 재로그인 방지) — Supabase signOut 보다 먼저.
    try {
      localStorage.removeItem('rof8_last_user');
      localStorage.removeItem('rof8_last_pw');
      localStorage.removeItem('rof8_remember');
      // Supabase 가 세션 토큰을 저장하는 localStorage 키 (sb-<project>-auth-token 형식) 도 청소
      for(let i = localStorage.length - 1; i >= 0; i--){
        const k = localStorage.key(i);
        if(k && k.indexOf('sb-') === 0 && /auth-token/.test(k)) localStorage.removeItem(k);
      }
    } catch(e){}
    // Supabase 세션 종료 (await — 완료까지 기다린 뒤 타이틀 복귀. 실패해도 진행)
    if(window.Backend && Backend.logoutAuth){
      try { await Backend.logoutAuth(); } catch(e){}
    }
    ['login-id','login-pw','signup-id','signup-pw','signup-pw2'].forEach(id=>{const e=document.getElementById(id);if(e)e.value='';});
    ['login-msg','signup-msg'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent='';});
    UI.show('title-screen');
  },
  // XP/Level is PER CARD, not global.
  // 2026-06-13: 곡선 개편 — `48 × L^0.55` (사용자 앵커: Lv1→2=승리 1판 / Lv1~10=15~20승).
  //   옛 `100 × L^1.5` (2026-05-02 C안) 은 Lv5 도달에 ~28매치로 체감 과중 → 동료 영웅레벨 게이팅 도입과 함께 완만화.
  //   Lv1→2: 48 / Lv10→11: 170 / Lv50→51: 413 / Lv99→100: 601. 누적 ~3.8만. (game-balance-tester 시뮬 검증)
  //   만렙(Lv100) 캡 — 그 이상 exp 부여 시 무시.
  CARD_LEVEL_CAP: 100,
  cardXpNext(card){
    const L=card.level||1;
    return Math.round(48*Math.pow(L,0.55));
  },
  giveCardXp(card,xp){
    if(!card)return false;
    if((card.level||1)>=this.CARD_LEVEL_CAP){card.xp=0;return false;}
    const fromLv=(card.level||1);
    card.xp=(card.xp||0)+xp;
    let leveled=false, pointsGained=0;
    while(card.xp>=this.cardXpNext(card)){
      if((card.level||1)>=this.CARD_LEVEL_CAP){card.xp=0;break;}
      card.xp-=this.cardXpNext(card);
      card.level=(card.level||1)+1;
      // 기획변경 2026-06-07: 자동 능력치(freePoints+5/lv) 폐기 → 5레벨마다 스탯포인트 1.
      // 즉시 분배(레벨업 오버레이) 또는 훈련소 수련 탭에서 분배. spec §5 / changelog 참조.
      if(card.level % 5 === 0){ card.freePoints=(card.freePoints||0)+1; pointsGained++; }
      leveled=true;
    }
    if(!leveled) return false;
    return { leveled:true, fromLv, toLv:(card.level||1), pointsGained };
  },
  // 스탯 포인트 분배 — 단일 정본 (레벨업 오버레이 + 훈련소 수련 탭 공용).
  // 대문자 필드(ATK/HP/SOUL) + 미러(cur/base/max) 갱신 → V4 카드 즉시 반영. SOUL 은 영웅 카드 좌상단 표시.
  allocStatPoint(card, stat){
    if(!card || (card.freePoints||0) <= 0) return false;
    if(stat !== 'atk' && stat !== 'hp' && stat !== 'soul') return false;
    card.freePoints -= 1;
    if(stat === 'atk'){ card.ATK=(card.ATK||0)+2; card.baseATK=card.ATK; card.curATK=card.ATK; }
    else if(stat === 'hp'){ card.HP=(card.HP||0)+5; card.maxHP=card.HP; card.curHP=card.HP; card.maxHp=card.HP; }
    else if(stat === 'soul'){ card.SOUL=(card.SOUL||0)+1; }
    if(!card.growthPts) card.growthPts={atk:0,hp:0,soul:0};
    card.growthPts[stat]=(card.growthPts[stat]||0)+1;
    return true;
  },
  giveCardHonor(card,honor){card.honor=(card.honor||0)+honor;},
  getHeroLevel(){const h=this.deck.find(c=>c.isHero);return h?(h.level||1):1;},
  // 동료 영입 슬롯 해금 — 영웅 레벨 마일스톤 (2026-06-13 사용자 결정). 동료 4명 고정, Lv1/3/6/10 → 1/2/3/4명.
  // 테이블 구동(튜닝 용이). _buildBattleDeck(formation, 70_formation_v6) + startQuestBattle(quest, 56_game_quests) 의 단일 진실.
  COMPANION_UNLOCK: [{lv:1,n:1},{lv:3,n:2},{lv:6,n:3},{lv:10,n:4}],
  getUnlockedCompanionCount(){
    const lv=this.getHeroLevel();
    let n=1;
    for(const t of this.COMPANION_UNLOCK){ if(lv>=t.lv) n=t.n; }
    return n;
  },
  /**
   * 프로필 카드 — 마을 좌상단 미니 일러스트에 쓸 카드.
   * profileCardId 가 유효한 보유 카드를 가리키면 그 카드, 아니면 영웅(default).
   * 카드 변경/삭제로 profileCardId 가 stale 해지면 자동 fallback.
   */
  getProfileCard(){
    if(this.profileCardId){
      const c = this.deck.find(c => c && c.uid === this.profileCardId);
      if(c) return c;
    }
    return this.deck.find(c => c && c.isHero) || null;
  },
  /** 프로필 카드 변경 — uid 입력.
   *  2026-05-13 사용자 결정: fixed 3종 (profile_m_warrior / profile_f_warrior / profile_titan) 만 허용.
   *  deck 카드 선택 폐기. */
  setProfileCard(uid){
    const FIXED = ['profile_m_warrior', 'profile_f_warrior', 'profile_titan'];
    if(!FIXED.includes(uid)) return false;
    this.profileCardId = uid;
    this.persist();
    return true;
  },
  /** 프로필 프레임 변경 — 2026-05-14 사용자 컨펌. 'none' 또는 'silver' 만 허용. */
  setProfileFrame(frameId){
    const ALLOWED = ['none', 'silver'];
    if(!ALLOWED.includes(frameId)) return false;
    this.profileFrameId = frameId;
    this.persist();
    return true;
  },
  getActionPoints(){const lv=this.getHeroLevel();if(lv>=50)return 4;if(lv>=10)return 3;if(lv>=2)return 2;return 1;},
  getTotalHonor(){return this.deck.reduce((s,c)=>s+(c.honor||0),0);},

  // ---- MENU ----
  // ── TOWN BUILDINGS ──
  // cost = array[5] for levels 1~5. level 0 = ruins.
  checkTutorial(trigger){
    if(this.tutStep>=this.TUT_STEPS.length)return;
    const step=this.TUT_STEPS[this.tutStep];
    if(step&&step.trigger===trigger){
      setTimeout(()=>this.showTutorial(),300);
    }
  },

  // ---- UPGRADE — now in Castle ----
});

// Expose for legacy onclick="Game.foo()" bindings in HTML strings.
// Same object identity — subsequent 5x_game_*.js augment via Object.assign.
window.Game = RoF.Game;