// Game Town (마을/건물/NPC/튜토리얼)
// Generated by docs/_split_game.py — Phase 4
// DO NOT hand-edit keys — edit in original and re-run splitter if needed.

RoF.__gameKeys = RoF.__gameKeys || new Set();
(function(keys){
  for (const k of keys) {
    if (RoF.__gameKeys.has(k)) {
      console.error('[Game] 중복 키 감지:', k);
      RoF.__gameKeyError = true;
    }
    RoF.__gameKeys.add(k);
  }
})(["BUILDINGS", "NPCS", "getNpc", "renderNpcBar", "showMenu", "TUT_STEPS", "showTutorial", "tutNext", "tutSkip", "getRelicSlots", "startBattleMatching"]);

Object.assign(RoF.Game, {
  // 2026-04-23 밤: 마을전경.png (1536×1024, 3:2, 10건물 체제) 기준 좌표 재설정
  // 2026-04-24: 증축·Lv 시스템 폐기 — cost/lvNames/lvDesc 필드 제거. 모든 건물 영구 활성.
  // x/y = 중심점 % / w/h = 크기 % (container 기준, aspect 3/2)
  BUILDINGS:[
    {id:'castle',  name:'왕궁',     icon:'🏰', desc:'퀘스트 & 동료 단련',                x:45.7, y:13.9, w:28.4, h:27.2, action:'showCastle'},
    {id:'temple',  name:'신전',     icon:'🔮', desc:'역대 점유자 & 명예의 전당',         x:49.1, y:36.8, w:21.5, h:18.6, action:'showTemple'},
    {id:'church',  name:'성당',     icon:'⛪', desc:'치료 & 장례',                        x:66.9, y:32.7, w:14.0, h:30.0, action:'showChurch'},
    {id:'forge',   name:'대장간',   icon:'⚒️', desc:'장비 제작 & 분해',                  x:21.8, y:45.0, w:21.1, h:21.0, action:'showForge'},
    {id:'training',name:'훈련소',   icon:'🏟️', desc:'보병 & 기병 수련',                  x:87.2, y:44.8, w:26.0, h:22.0, action:'showTraining'},
    {id:'tavern',  name:'선술집',   icon:'🍺', desc:'용병 고용',                          x:21.4, y:69.5, w:20.0, h:23.8, action:'showTavern'},
    {id:'library', name:'도서관',   icon:'📋', desc:'전력 편성 & 생명의 서',             x:46.1, y:57.1, w:15.7, h:21.6, action:'showDeckView'},
    {id:'shop',    name:'암시장',   icon:'🎭', desc:'비전 · 유물 · 6 원소 로테이션',     x:64.2, y:63.9, w:17.4, h:19.3, action:'showShop'},
    {id:'inn',     name:'여관',     icon:'🛏️', desc:'여행자 거점 (TBD)',                 x:87.2, y:69.6, w:26.5, h:24.8, action:'showInn'},
    {id:'gate',    name:'성문',     icon:'🚪', desc:'리그 · 원정 · 결투 출전',          x:51.5, y:86.8, w:33.1, h:26.3, action:'startBattleMatching'},
  ],

  // ── BUILDING NPCs (2026-04-24: 선택지 메뉴 시스템) ──
  // 각 NPC: { icon, name, greet, choices: [{label, action, modal?, comingSoon?}], chat?: '한 줄 더' }
  //   greet  = 진입 시 한 줄 인사 (.npc-dialog-text 에 표시).
  //   choices = 1~4개 선택지 버튼. action 은 RoF.Game 메서드 이름 또는 'modal' / 'chat' / 'close'.
  //     - comingSoon: true → 라벨에 (준비 중) 표기 + 클릭 시 modal 텍스트로 안내.
  //     - modal: comingSoon 시 표시할 모달 (title, body).
  //   chat   = 선택지 [대화하기] (Q1 a 안 — 한 줄 더) 클릭 시 표시할 텍스트. 그 후 자동 닫힘.
  //   매번 진입 시 표시 (Q2 A 안 — sessionStorage seen 플래그도 폐기).
  //   이미지: img/npc_{buildingId}_1.png. 미공급 시 큰 emoji fallback.
  NPCS:{
    castle: {
      icon:'👴', name:'늙은 조언자',
      greet:'영웅이여, 어떤 일로 오셨소?',
      choices:[
        // 2026-05-02: 단련은 훈련장으로 분리. 왕궁 = 퀘스트 + 전직 (전직 placeholder).
        {label:'퀘스트 받기',   action:'showCastleQuestEntry'},
        {label:'전직 알아보기', action:'modal', comingSoon:true,
          modal:{title:'⚜️ 전직', body:'영웅의 새 길이 곧 열립니다.\n\n(전직 시스템 준비 중)'}},
        {label:'대화하기',      action:'chat'},
      ],
      chat:'운명의 왕좌까지 가는 길은 멀다오. 한 걸음씩, 천천히 가시오.',
    },
    temple: {
      icon:'🔮', name:'신전 사제',
      greet:'옛 신들의 기록을 보시겠습니까?',
      choices:[
        {label:'역대 점유자 둘러보기', action:'modal', comingSoon:true,
          modal:{title:'🔮 역대 점유자 회랑', body:'제1세대 6 신부터 현 세대까지의 점유자 기록이 곧 열립니다.\n\n(역대 점유자 회랑 준비 중)'}},
        {label:'명예의 전당 보기',     action:'modal', comingSoon:true,
          modal:{title:'🏛️ 명예의 전당', body:'영원히 기억될 영웅들의 이름이 곧 새겨질 것입니다.\n\n(명예의 전당 준비 중)'}},
        {label:'대화하기',             action:'chat'},
      ],
      chat:'여섯의 신전마다 사연이 있지요... 언젠가 모두 들려드리겠습니다.',
    },
    church: {
      icon:'🙏', name:'수녀',
      greet:'신의 축복이 함께하시길.',
      choices:[
        // 2026-05-02: guard 확장 — 영웅 포함 + 부분 손상 카드도 검사 (showChurch filter 와 일치)
        {label:'부상자 회복하기', action:'showChurch',
          guard:(g)=>g.deck.some(c=>{
            if(c.injured)return true;
            const hp=c.currentHp!=null?c.currentHp:c.hp;
            return hp<c.hp;
          }),
          denyMsg:'지금은 부상자가 없네요. 신께서 모두를 보살피셨군요.'},
        {label:'장례 치르기',     action:'showChurch',
          guard:(g)=>g.deck.some(c=>c.injured&&!c.isHero),
          denyMsg:'장례를 치를 동료가 없습니다. 다행한 일이지요.'},
        {label:'대화하기',        action:'chat'},
      ],
      chat:'신께서는 모두를 굽어보십니다. 영웅이든, 동료든.',
    },
    forge: {
      icon:'👦', name:'견습공',
      greet:'뭐… 뭐 만들어 드릴까요?',
      choices:[
        {label:'장비 제작하기', action:'modal', comingSoon:true,
          modal:{title:'⚒️ 장비 제작', body:'대장간 제작 기능이 곧 열립니다.\n\n(장비 제작 시스템 준비 중)'}},
        {label:'장비 분해하기', action:'modal', comingSoon:true,
          modal:{title:'⚒️ 장비 분해', body:'장비 분해 기능이 곧 열립니다.\n\n(분해 시스템 준비 중)'}},
        {label:'대화하기',      action:'chat'},
      ],
      chat:'언젠가 저도... 진짜 대장장이가 될 거예요.',
    },
    training: {
      icon:'👦', name:'허수아비',
      greet:'...저를 때려도 됩니다.',
      choices:[
        // 2026-05-10: 단련 시스템 임시 폐기 (사용자 결정). 화면/코드는 보존, NPC choice 만 제거.
        {label:'스킬 교체', action:'showTrainingSkillEntry'},        // showTraining + showTrainingSkillTab
        {label:'대화하기', action:'chat'},
      ],
      chat:'...언젠가는, 저도 움직일 수 있을까요?',
    },
    tavern: {
      icon:'🧑', name:'주막주인',
      greet:'어서 와! 한 잔 할래?',
      choices:[
        // 2026-04-29: 영웅 = 유저 카드 1장 고정. 선술집 영웅 영입 폐기. 전직은 왕궁에서.
        {label:'용병 고용하기', action:'showTavern'},
        {label:'대화하기',      action:'chat'},
      ],
      chat:'세상엔 별의별 사연 가진 놈들이 모인다구. 언제든 들러.',
    },
    library: {
      icon:'📖', name:'서생',
      greet:'조용히 살펴보시면 됩니다.',
      choices:[
        // 2026-04-28: showDeckTab/CodexTab 은 탭 전환 메서드라 화면 진입 wrapper 로 변경.
        {label:'전력 열람',         action:'showDeckView'},   // deck 이 default 탭
        {label:'생명의 서 확인하기', action:'showBookOfLife'},  // Step 6 — RoF.BookOfLife.show() (시안 통째 이식)
        {label:'대화하기',          action:'chat'},
      ],
      chat:'기록은 거짓말을 하지 않지요. 영웅의 발자취도, 적의 약점도.',
    },
    shop: {
      icon:'👵', name:'행상인',
      greet:'어머나~ 손님!',
      choices:[
        {label:'상품 둘러보기', action:'modal', comingSoon:true,
          modal:{title:'🎭 암시장', body:'비전과 유물 6 원소 로테이션 상점이 곧 문을 엽니다.\n\n(암시장 시스템 준비 중)'}},
        {label:'대화하기',      action:'chat'},
      ],
      chat:'좋은 물건은 좋은 손님에게만 보여드린답니다, 호호.',
    },
    inn: {
      icon:'🛏️', name:'여관 주인',
      greet:'어서 오세요, 여행자여. 잠시 쉬어 가시지요.',
      choices:[
        // 2026-05-02: 여관 = 에너지 회복 전담. HP 회복은 성당으로 이동.
        {label:'에너지 회복하기', action:'showInn',
          guard:(g)=>g.deck.some(c=>!c.injured && (c.curNrg!=null?c.curNrg:0)<(c.nrg||0)),
          denyMsg:'에너지가 모두 만전이시군요. 지금은 쉬실 필요 없겠어요.'},
        {label:'정보 듣기', action:'modal', comingSoon:true,
          modal:{title:'🛏️ 여관 소문', body:'먼 곳의 소문과 정보가 곧 들려올 것입니다.\n\n(정보 시스템 준비 중)'}},
        {label:'대화하기',  action:'chat'},
      ],
      chat:'먼 길 오셨군요. 부디 무탈하시길.',
    },
    gate: {
      icon:'👦', name:'소년 파수꾼',
      greet:'싸우러 나가실 건가요?',
      choices:[
        {label:'전열 정비하기',   action:'showFormation'},
        {label:'리그 도전하기',   action:'startBattleMatching'},
        {label:'원정대 모집하기', action:'modal', comingSoon:true,
          modal:{title:'🚪 원정대', body:'동료들과 함께 보스 토벌에 나서는 기능이 곧 열립니다.\n\n(원정대 시스템 준비 중)'}},
        // 2026-05-02: 결투장 준비중으로 변경 (사용자 결정).
        {label:'결투장 입장하기', action:'modal', comingSoon:true,
          modal:{title:'⚔️ 결투장', body:'다른 영주의 영웅과 1:1 결투를 벌이는 결투장이 곧 열립니다.\n\n(결투장 시스템 준비 중)'}},
      ],
      // gate 는 핵심 기능 4개라 chat 옵션 없음 — 4 선택지로 충분.
    },
  },

  getNpc(buildingId){
    const npc = this.NPCS[buildingId];
    if(!npc) return { icon:'❓', name:'???', greet:'...', img:'', choices:[] };
    return { ...npc, img: `img/npcs/npc_${buildingId}_1.png` };
  },

  renderNpcBar(buildingId,contextMsg){
    const npc=this.getNpc(buildingId);
    const msg=contextMsg||npc.greet;
    // 2026-04-24: 56×56 원형 → 반신샷 세로 박스로 전환 (.npc-portrait CSS 단일 소스).
    //   원본 이미지 500×750 (~500×799) 을 object-position 상단 기준으로 얼굴부터 허리까지 노출.
    const iconHtml=npc.img
      ? `<img class="npc-portrait" src="${npc.img}" alt="${npc.name}">`
      : `<span class="npc-emoji" aria-hidden="true">${npc.icon}</span>`;
    return `<div class="npc-bar"><div class="npc-icon">${iconHtml}</div><div class="npc-speech"><div class="npc-name">${npc.name}</div><div class="npc-text">"${msg}"</div></div></div>`;
  },

  showMenu(){
    // 매치 진행 중 + 매치 화면 active → 자동 항복 처리 (2026-05-12)
    // 매치 도중 menu 가려는 시도 = 항복 의미. surrenderMatch 가 확인 후 패배 + 보상.
    const _mst = RoF.Match && RoF.Match.state;
    const _tcgActive = document.getElementById('tcg-screen')?.classList.contains('active');
    if (_mst && !_mst.winner && _tcgActive && typeof this.surrenderMatch === 'function') {
      return this.surrenderMatch();
    }
    UI.show('menu-screen');SFX.bgm('town');
    const hero=this.deck.find(c=>c.isHero);
    const hLv=hero?(hero.level||1):1;
    const lg=this.getLeague();const lp=this.leaguePoints||0;

    // HUD — 2026-05-03: menu-welcome → 프로필 슬롯 (이미지 + 닉/Lv 분리). getProfileCard() = 영웅 default + profileCardId 우선.
    // 2026-05-13: 프로필 카드 3종 (m_warrior/f_warrior/titan) 만 사용. 영웅 카드 id → 얼굴 자산 lookup.
    const profileCard = (typeof this.getProfileCard === 'function') ? this.getProfileCard() : hero;
    const profImgEl = document.getElementById('town-profile-img');
    if(profImgEl){
      // 2026-05-13 사용자 결정: 프로필 = profileCardId 직접 매핑 (fixed 3종) + 영웅 성별 default.
      const PROFILE_SRC = {
        'profile_m_warrior': 'img/heroes/m_warrior/profile.png',
        'profile_f_warrior': 'img/heroes/f_warrior/profile.png',
        'profile_titan':     'img/npcs/profile_titan.png',
      };
      // default = 영웅 카드의 성별 (m/f) 기반 자동 매핑. heroCard.img 가 protagonist_<gender>_*.png.
      let defaultId = 'profile_m_warrior';
      if(hero && hero.img){
        if(hero.img.indexOf('protagonist_f_') === 0) defaultId = 'profile_f_warrior';
        else if(hero.img.indexOf('protagonist_m_') === 0) defaultId = 'profile_m_warrior';
      }
      const pid = this.profileCardId || defaultId;
      const src = PROFILE_SRC[pid] || PROFILE_SRC[defaultId];
      profImgEl.style.backgroundImage = `url('${src}')`;
      profImgEl.classList.remove('is-empty');
      // 2026-05-14 사용자 컨펌 — profileFrameId 따라 frame overlay 토글 (silver 호박금 톤)
      const frameId = this.profileFrameId || 'none';
      let frameOverlay = profImgEl.querySelector('.profile-frame-overlay');
      if(frameId !== 'none'){
        if(!frameOverlay){
          frameOverlay = document.createElement('div');
          frameOverlay.className = 'profile-frame-overlay';
          profImgEl.style.position = 'relative';
          profImgEl.appendChild(frameOverlay);
        }
      } else if(frameOverlay){
        frameOverlay.remove();
      }
    }
    const profNameEl = document.getElementById('town-profile-name');
    if(profNameEl) profNameEl.textContent = Auth.heroName || Auth.user || '—';
    const profLvEl = document.getElementById('town-profile-lv');
    // 프로필 카드의 Lv 표시 (영웅 = hLv, 다른 카드는 그 카드의 Lv)
    const profLv = profileCard ? (profileCard.level || 1) : hLv;
    if(profLvEl) profLvEl.textContent = `Lv.${profLv}`;
    document.getElementById('town-league').innerHTML=`<span style="color:${lg.color};">${lg.icon} ${lg.name} (${lp}점)</span>`;
    document.getElementById('town-gold').textContent=this.gold;
    document.getElementById('town-bless').textContent=this.blessings||0;
    // 추가 화폐 표시
    const gemsEl=document.getElementById('town-gems');
    if(gemsEl)gemsEl.textContent=this.gems||0;
    const graceEl=document.getElementById('town-grace');
    if(graceEl)graceEl.textContent=this.divineGrace||0;
    document.getElementById('town-ap').innerHTML=`⚡<span>${this.getActionPoints()}</span>`;
    document.getElementById('town-deck-count').textContent=this.deck.length;
    const injuredCount=this.deck.filter(c=>c.injured&&!c.isHero).length;
    const existingInj=document.getElementById('town-injured');
    if(existingInj)existingInj.remove();
    if(injuredCount>0){
      const injEl=document.createElement('div');injEl.className='th-stat';injEl.id='town-injured';
      injEl.innerHTML=`<span style="color:#ff4444;">⚠ 부상 ${injuredCount}</span>`;
      document.querySelector('.town-hud-right').appendChild(injEl);
    }

    // Stars
    const sky=document.getElementById('town-sky');
    if(!sky.children.length){for(let i=0;i<30;i++){const s=document.createElement('div');s.className='star';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.animationDelay=Math.random()*3+'s';sky.appendChild(s);}}

    // Buildings
    const tc=document.getElementById('town-container');
    // 2026-04-24: 배경 video 는 유지하고 건물 divs 만 제거 (innerHTML='' 금지)
    tc.querySelectorAll('.town-building').forEach(el=>el.remove());
    // 빈 곳 클릭 시 선택 해제
    tc.onclick=(e)=>{if(e.target===tc)document.querySelectorAll('.town-building.selected').forEach(el=>el.classList.remove('selected'));};
    // 2026-04-24: 증축·Lv 시스템 폐기 — 모든 건물 영구 활성. tb-upgrade 버튼 / Lv 라벨 / built/ruins 분기 모두 제거.
    this.BUILDINGS.forEach(b=>{
      const div=document.createElement('div');
      div.className='town-building built';
      div.setAttribute('data-id', b.id);
      // 편집기로 설정한 크기(%) 기준 중심점 배치
      div.style.left=b.x+'%';
      div.style.top=b.y+'%';
      div.style.width=(b.w||14)+'%';
      div.style.height=(b.h||28)+'%';
      div.style.transform='translate(-50%,-50%)';
      // 2026-05-05: img/town/{id}.png 단일 경로. 누락 시 자기 자신 hide (404 누적 방지).
      // 기존 building_{id}.png fallback 은 폐기 — 두 번째 onerror 도 같은 fail 이라 누적되던 버그 (콘솔 3000+ 에러).
      // 자산 미공급 건물(temple/gate/inn)은 placeholder transparent PNG (256×256) 로 채움 → 자리만 비고 라벨 노출.
      const bImg = `img/town/${b.id}.png`;
      const imgStyle=`width:100%;height:100%;object-fit:contain;border-radius:0;`;
      // castle 은 이미지가 커서 라벨을 성 본체 중앙(55%) 에 오버레이. 나머지는 이미지 위쪽.
      const labelPos = (b.id==='castle')
        ? 'position:absolute;top:55%;left:50%;transform:translate(-50%,-50%);white-space:nowrap;'
        : 'position:absolute;top:-22px;left:50%;transform:translateX(-50%);white-space:nowrap;';
      div.innerHTML=`<div class="tb-icon" style="width:100%;height:100%;"><img src="${bImg}" onerror="this.style.display='none'" style="${imgStyle}"></div><div class="tb-label" style="${labelPos}">${b.name}</div>`;
      // 2026-04-24: 한 번 클릭 = 즉시 NPC 다이얼로그 (선택지 메뉴). 두 번 클릭 패턴 폐기.
      // gate 포함 모든 건물 동일 흐름. action 라우팅은 NPCS.choices 가 담당.
      const openDialog = (e)=>{ e.stopPropagation(); SFX.play('click'); this.showBuildingDialog(b.id); };
      div.querySelector('.tb-icon').onclick = openDialog;
      div.querySelector('.tb-label').onclick = openDialog;
      tc.appendChild(div);
    });

    // Walking NPCs 제거 (2026-04-14) — 사람·전투 이모티콘 애니메이션 삭제
    document.querySelectorAll('.town-npc').forEach(el=>el.remove());

    // 2026-04-24: Deck preview 삭제 (menu-deck DOM 제거). 덱 확인은 도서관에서.
    this.persist();
    // Tutorial triggers (2026-04-24: *_built / first_upgrade 트리거 제거 — 건물은 항상 활성)
    this.checkTutorial('town_first');
    if(this.totalWins+this.totalGames>0&&this.tutStep===2)this.checkTutorial('back_after_first');
    if(this.deck.some(c=>c.injured&&!c.isHero)&&this.tutStep===6)this.checkTutorial('first_injury');
  },

  // 2026-04-24: 증축·Lv 시스템 폐기 — buildBuilding / upgradeBuilding / showUpgrade / getBuildingLv / initBuildings 모두 제거.

  // 2026-04-24: 튜토리얼 재작성 — 건물 짓기·단련 안내 제거, "탐방" 흐름으로 압축.
  // 14단계 → 8단계. *_built / first_upgrade / first_stat_alloc / first_recruit 트리거 폐기.
  TUT_STEPS:[
    {id:0,trigger:'town_first',speaker:'companion',text:'안녕, 나는 {name}. 신께서 당신을 돕도록 보내셨어.\n여기가 우리의 영지야. 모든 건물이 이미 준비돼 있어.\n먼저 도서관에서 우리 전력을 살펴보자.',highlight:'library'},
    {id:1,trigger:'first_battle',speaker:'companion',text:'출전할 동료를 고르는 거야. 영웅은 자동 출전!\n내가 옆에서 싸워줄 테니 걱정 마.\n참, 영웅이 쓰러지면 지는 거니까 조심해!'},
    {id:2,trigger:'first_survive',speaker:'companion',text:'해냈어! 라운드를 버텼다!\n이제 행동력을 써서 동료를 소환하거나 전투기술을 익힐 수 있어.\n시간 제한이 있으니까 빨리 판단해!'},
    {id:3,trigger:'first_battle_end',speaker:'companion',text:'첫 전투 끝! 전리품 상자를 잘 골라봐.\n마을로 돌아가서 동료를 더 모으거나 단련시키자.\n운명의 왕좌까지... 아직 멀지만 같이 가보자!'},
    {id:4,trigger:'back_after_first',speaker:'companion',text:'골드가 생겼네! 선술집에 가면 함께 싸울 동료를 영입할 수 있어.\n그리고 왕궁에서는 동료를 단련시켜 더 강하게 만들 수 있지.\n둘 다 들러봐!',highlight:'tavern'},
    {id:5,trigger:'first_defeat',speaker:'companion',text:'패전했지만 걱정 마!\n영웅은 신의 축복으로 반드시 되살아나.\n하지만 동료들은... 부상을 입을 수 있어.\n성당에서 치유하거나 장례를 치러줘야 해.'},
    {id:6,trigger:'first_injury',speaker:'companion',text:'부상당한 동료가 있어!\n성당에 가서 치유하자. 부상 상태로는 출전할 수 없어!',highlight:'church'},
    {id:7,trigger:'reach_silver',speaker:'companion',text:'실버 리그 달성! 대단한데?\n이제부터 진짜 강한 도전자들이 나타날 거야.\n대장간이나 암시장도 둘러보면 좋겠지. 멈추지 말고 나아가자!'},
  ],

  showTutorial(){
    const step=this.TUT_STEPS.find(s=>s.id===this.tutStep);
    if(!step||this.tutStep>=this.TUT_STEPS.length)return;
    const cName=this.companionName||'동료';
    const comp=this.deck.find(c=>c.isCompanion);
    const cIcon=comp?comp.icon:'🗡️';
    // Resolve speaker
    let speakerLabel=step.speaker;
    if(step.speaker==='companion')speakerLabel=`${cIcon} ${cName}`;
    // Replace {name} in text
    const text=step.text.replace(/\{name\}/g,cName);
    // Create overlay
    const ov=document.createElement('div');ov.className='tut-overlay';ov.id='tut-overlay';
    const box=document.createElement('div');box.className='tut-box';
    box.innerHTML=`<div class="tut-speaker">${speakerLabel}</div>
      <div class="tut-text">${text.replace(/\n/g,'<br>')}</div>
      <div style="display:flex;gap:8px;justify-content:center;">
        <button class="btn btn-s" onclick="Game.tutNext()">확인</button>
        <button class="btn btn-s btn-red" onclick="Game.tutSkip()" style="font-size:.7rem;">튜토리얼 끄기</button>
      </div>`;
    ov.appendChild(box);document.body.appendChild(ov);
    // Highlight building
    if(step.highlight){
      const bEls=document.querySelectorAll('.town-building');
      bEls.forEach(el=>{
        const label=el.querySelector('.tb-label');
        if(label&&label.textContent.includes(this.BUILDINGS.find(b=>b.id===step.highlight)?.name)){
          el.classList.add('tut-highlight');
        }
      });
    }
  },
  tutNext(){
    const ov=document.getElementById('tut-overlay');if(ov)ov.remove();
    document.querySelectorAll('.tut-highlight').forEach(el=>el.classList.remove('tut-highlight'));
    this.tutStep++;this.persist();
  },
  tutSkip(){
    const ov=document.getElementById('tut-overlay');if(ov)ov.remove();
    document.querySelectorAll('.tut-highlight').forEach(el=>el.classList.remove('tut-highlight'));
    this.tutStep=99;this.persist();
  },
  // ═════════════════════════════════════════════════════════════
  // NPC DIALOG (2026-04-24 재설계) — 매 진입 시 큰 반신 + 한 줄 인사 + 선택지 메뉴
  //
  // 흐름:
  //   1. 건물 클릭 → showBuildingDialog(buildingId)
  //   2. .npc-dialog-overlay 활성 (큰 반신 500×720, npc.img 또는 emoji fallback)
  //   3. NPC 한 줄 인사 (npc.greet) + 선택지 버튼 1~4개 (npc.choices)
  //   4. 선택지 클릭 → _runChoiceAction:
  //        - action 이 RoF.Game 메서드명 → 그 메서드 호출 + 오버레이 닫힘
  //        - action 'modal' + comingSoon → UI.modal 표시 + 오버레이 닫힘
  //        - action 'chat' → npc.chat 한 줄 표시 + [닫기] 버튼만 노출
  //   5. ESC / 돌아가기 → 즉시 닫힘 (액션 없음, 마을 복귀)
  //
  // 시퀀스(scenes) / seen 플래그(sessionStorage) 모두 폐기 — 매번 보여주는 게 일관됨.
  // ═════════════════════════════════════════════════════════════
  _npcDialogState: null,   // {buildingId, npc, mode:'choices'|'chat'}
  _npcEscHandler: null,

  showBuildingDialog(buildingId){
    const npc = this.getNpc(buildingId);
    if(!npc || (!npc.choices && !npc.greet)){
      // 안전장치: 데이터 없으면 액션 없이 무시
      return;
    }
    this._npcDialogState = { buildingId, npc, mode:'choices' };
    this._openNpcDialogOverlay();
    this._renderNpcArt(npc);
    this._renderNpcDialog();
  },

  _openNpcDialogOverlay(){
    const ov = document.getElementById('npc-dialog-overlay');
    if(!ov) return;
    ov.classList.add('active');
    if(this._npcEscHandler) document.removeEventListener('keydown', this._npcEscHandler, true);
    this._npcEscHandler = (e) => {
      if(e.key === 'Escape'){ e.preventDefault(); this._closeNpcDialog(); }
    };
    document.addEventListener('keydown', this._npcEscHandler, true);
  },

  _closeNpcDialog(){
    const ov = document.getElementById('npc-dialog-overlay');
    if(ov) ov.classList.remove('active');
    if(this._npcEscHandler){
      document.removeEventListener('keydown', this._npcEscHandler, true);
      this._npcEscHandler = null;
    }
    this._npcDialogState = null;
  },

  /** 큰 반신 art 렌더 (이미지 우선, 404 시 큰 emoji fallback) */
  _renderNpcArt(npc){
    const artEl = document.getElementById('npc-dialog-art');
    if(!artEl) return;
    const artParent = artEl.parentElement;
    let fallbackEl = artParent ? artParent.querySelector('.npc-dialog-fallback') : null;
    if(artParent && !fallbackEl){
      fallbackEl = document.createElement('div');
      fallbackEl.className = 'npc-dialog-fallback';
      artParent.appendChild(fallbackEl);
    }
    if(fallbackEl) fallbackEl.textContent = (npc && npc.icon) || '👤';
    if(npc.img){
      artEl.src = npc.img;
      artEl.classList.remove('hidden');
      artEl.onerror = function(){ this.classList.add('hidden'); };
    } else {
      artEl.classList.add('hidden');
    }
  },

  /** 인사 + 선택지 버튼 또는 chat 한 줄 + 닫기 버튼 렌더 */
  _renderNpcDialog(){
    const st = this._npcDialogState;
    if(!st) return;
    const { npc, mode } = st;
    const nameEl = document.getElementById('npc-dialog-name');
    const textEl = document.getElementById('npc-dialog-text');
    const choicesEl = document.getElementById('npc-dialog-choices');
    if(nameEl) nameEl.textContent = (npc.icon || '') + ' ' + (npc.name || '');
    if(mode === 'chat'){
      if(textEl) textEl.textContent = npc.chat || '...';
      if(choicesEl) choicesEl.innerHTML = `<button class="btn btn-s npc-choice-btn" data-action="game._closeNpcDialog">닫기</button>`;
      return;
    }
    if(textEl) textEl.textContent = npc.greet || '';
    if(choicesEl){
      const buttons = (npc.choices || []).map((c, idx) => {
        const labelSuffix = c.comingSoon ? ' <span class="npc-choice-soon">(준비 중)</span>' : '';
        return `<button class="btn btn-s npc-choice-btn" data-choice-idx="${idx}">${c.label}${labelSuffix}</button>`;
      }).join('');
      const back = `<button class="btn btn-s btn-red npc-choice-btn npc-choice-back" data-action="game._closeNpcDialog">돌아가기</button>`;
      choicesEl.innerHTML = buttons + back;
      // 선택지 버튼 바인딩
      choicesEl.querySelectorAll('button[data-choice-idx]').forEach(btn => {
        btn.addEventListener('click', (e) => {
          const idx = parseInt(btn.getAttribute('data-choice-idx'), 10);
          this._runChoiceAction(idx);
        });
      });
    }
  },

  /** 선택지 클릭 핸들러 — chat / modal / 메서드명 분기 */
  _runChoiceAction(idx){
    const st = this._npcDialogState;
    if(!st) return;
    const choice = st.npc.choices && st.npc.choices[idx];
    if(!choice) return;
    if(typeof SFX !== 'undefined' && SFX.play) SFX.play('click');
    // 2026-04-27: guard 미충족 시 화면전환 없이 NPC 거절 대사 (chat 모드 재사용).
    // 예: 교회에 부상자 0명 → 수녀가 "지금은 부상자가 없네요" 그 자리에서 답함.
    if(typeof choice.guard === 'function' && !choice.guard(this)){
      st.mode = 'chat';
      st.npc = Object.assign({}, st.npc, { chat: choice.denyMsg || '지금은 어렵겠네요.' });
      this._renderNpcDialog();
      return;
    }
    // 'chat' — npc.chat 한 줄 표시 모드 전환 (오버레이 유지)
    if(choice.action === 'chat'){
      st.mode = 'chat';
      this._renderNpcDialog();
      return;
    }
    // comingSoon + modal — 모달 띄우고 오버레이 닫음
    if(choice.action === 'modal' && choice.modal){
      this._closeNpcDialog();
      UI.modal(choice.modal.title, choice.modal.body, null);
      return;
    }
    // 그 외 — RoF.Game 메서드명. 닫고 메서드 호출.
    this._closeNpcDialog();
    if(typeof this[choice.action] === 'function'){
      this[choice.action]();
    } else if(typeof Arena !== 'undefined' && typeof Arena[choice.action] === 'function'){
      // PvP 매칭은 Arena 네임스페이스
      Arena[choice.action]();
    } else {
      console.warn('[npc-dialog] action not found:', choice.action);
    }
  },

  /** 2026-05-16 — '리그 도전하기' / 성문 클릭 시 매칭 직행 (formation 매칭 흐름 동일).
      사용자 명시: "리그 도전하기 = 출전 시작 = 매칭 찾기". 옛 게임 load 흐름 폐기.
      별도 이름: RoF.Game.startBattle (61_match_ui.js 정의) 가 회귀/dev navigator 용
      D-1 placeholder 직접 매치 흐름이라 이름 충돌 회피. */
  startBattleMatching(){
    if(typeof RoF !== 'undefined' && RoF.Formation && typeof RoF.Formation.startBattle === 'function'){
      RoF.Formation.startBattle();
    } else {
      console.warn('[town] RoF.Formation.startBattle 미정의');
    }
  },

  /** 게이트 [전열 정비하기] / 다른 진입점에서 사용 — Formation 화면 직접 진입 */
  showFormation(){
    if(typeof RoF !== 'undefined' && RoF.Formation && typeof RoF.Formation.show === 'function'){
      RoF.Formation.show();
    } else {
      UI.show('formation-screen');
    }
  },

  /** 성/도서관 NPC 메뉴 [생명의 서 확인하기] 진입 — RoF.BookOfLife.show() 위임. */
  showBookOfLife(){
    if(typeof RoF !== 'undefined' && RoF.BookOfLife && typeof RoF.BookOfLife.show === 'function'){
      RoF.BookOfLife.show();
    } else {
      UI.show('book-of-life-screen');
    }
  },

  /** 2026-05-18 사용자 명시 — 전열정비/생명의서 돌아가기 = 마을 (menu-screen). showMenu alias. */
  showTown(){
    this.showMenu();
  },

  // ---- DECK VIEW (상태확인) ----
  getRelicSlots(){return Math.max(1,Math.floor(this.getHeroLevel()/2));},
  // 2026-05-05 PHASE 6: 옛 55_game_battle.js trash 시 함께 사라진 헬퍼 임시 복원.
  // PHASE 6 보드 6명 (영웅 1 + 유닛 5, BOARD_MAX=5). 2026-06-13 stale 7→6 정정 (실 enforcement 는 60_turnbattle BOARD_MAX, 여긴 dv-slots 표시값).
  /* diagnosis-confirmed: 2026-06-13 사유: refactor — 보드 한도 doc 모순 정정(표시값 7→6, BOARD_MAX 정합). 버그수정/전투로직 변경 아님. */
  getCommandSlots(){return 6;},

  // === LEAGUE SYSTEM ===
});
