// Game Deck (덱 보기/도감/카드 상세)
// Generated by docs/_split_game.py — Phase 4
// DO NOT hand-edit keys — edit in original and re-run splitter if needed.

RoF.__gameKeys = RoF.__gameKeys || new Set();
(function(keys){
  for (const k of keys) {
    if (RoF.__gameKeys.has(k)) {
      console.error('[Game] 중복 키 감지:', k);
      RoF.__gameKeyError = true;
    }
    RoF.__gameKeys.add(k);
  }
})(["_dvTab", "showDeckTab", "showCodexTab", "showCodexView", "_codexFilter", "_codexKind", "showCodexUnits", "showCodexSkills", "renderCodex", "_renderCodexUnits", "_renderCodexSkills", "showCodexDetail", "_CODEX_KIND_KO", "_CODEX_DMG_KO", "_CODEX_KW_KO", "showDeckView", "equipOwnedSkill", "showDeckCardFocus", "closeDeckCardFocus", "showRelicDetail", "equipSkill"]);

Object.assign(RoF.Game, {
  _dvTab:'deck',
  showDeckTab(){
    this._dvTab='deck';
    document.getElementById('deck-tab').style.display='';
    document.getElementById('codex-tab').style.display='none';
    document.getElementById('tab-deck').style.borderColor='#ffd700';document.getElementById('tab-deck').style.color='#ffd700';
    document.getElementById('tab-codex').style.borderColor='';document.getElementById('tab-codex').style.color='';
  },
  showCodexTab(){
    this._dvTab='codex';
    document.getElementById('deck-tab').style.display='none';
    document.getElementById('codex-tab').style.display='';
    document.getElementById('tab-codex').style.borderColor='#ffd700';document.getElementById('tab-codex').style.color='#ffd700';
    document.getElementById('tab-deck').style.borderColor='';document.getElementById('tab-deck').style.color='';
    this.renderCodex();
  },
  // 2026-05-10: 생명의 서 sub-tab (동료/스킬) 전환
  _codexKind:'units',
  showCodexUnits(){
    this._codexKind='units';
    const u=document.getElementById('codex-sub-units'), s=document.getElementById('codex-sub-skills');
    if(u){ u.style.borderColor='#ffd700'; u.style.color='#ffd700'; }
    if(s){ s.style.borderColor='';        s.style.color='';        }
    this._codexFilter='all';  // sub-tab 전환 시 필터 초기화
    this.renderCodex();
  },
  showCodexSkills(){
    this._codexKind='skills';
    const u=document.getElementById('codex-sub-units'), s=document.getElementById('codex-sub-skills');
    if(s){ s.style.borderColor='#ffd700'; s.style.color='#ffd700'; }
    if(u){ u.style.borderColor='';        u.style.color='';        }
    this._codexFilter='all';  // sub-tab 전환 시 필터 초기화
    this.renderCodex();
  },
  // 2026-04-28: 도서관 NPC "생명의 서 확인하기" 진입용 wrapper.
  // 2026-05-10 재작성: showDeckView() 가 formation 으로 redirect 되어 codex 진입 단절.
  //                    codex 는 전열 정비와 별개 도감 → deckview-screen 직접 활성화 + codex-tab 만 노출.
  showCodexView(){
    UI.show('deckview-screen');
    const nameEl = document.getElementById('dv-name');
    if(nameEl) nameEl.textContent = `📖 생명의 서`;
    // deck-tab 숨기고 codex-tab 만 노출 (옛 "전력 열람"/"생명의 서" 탭 + lib-npc 모두 hide)
    const deckTab = document.getElementById('deck-tab');     if(deckTab) deckTab.style.display='none';
    const codexTab = document.getElementById('codex-tab');   if(codexTab) codexTab.style.display='';
    const tabDeck  = document.getElementById('tab-deck');    if(tabDeck)  tabDeck.style.display='none';
    const tabCodex = document.getElementById('tab-codex');   if(tabCodex) tabCodex.style.display='none';
    const oldNpc   = document.getElementById('lib-npc');     if(oldNpc)   oldNpc.remove();
    this._dvTab = 'codex';
    this._codexKind = 'units';   // default sub-tab
    this._codexFilter = 'all';
    this.renderCodex();
  },
  _codexFilter:'all',
  // 2026-05-10: sub-tab (units/skills) 분기. 공통 = 필터 버튼 렌더 + grid clear.
  renderCodex(filter){
    if(filter)this._codexFilter=filter;
    const f=this._codexFilter;
    const k=this._codexKind||'units';
    // 공통 필터 버튼 (수집/미수집/등급별)
    const fd=document.getElementById('codex-filters');fd.innerHTML='';
    const filters=[
      {id:'all',label:'전체'},
      {id:'owned',label:'수집'},
      {id:'missing',label:'미수집'},
      {id:'bronze',label:'일반'},
      {id:'silver',label:'희귀'},
      {id:'gold',label:'고귀한'},
      {id:'legendary',label:'전설의'},
      {id:'divine',label:'신'},
    ];
    // 스킬 sub-tab 추가 필터: 시그니처 / 중립
    if(k==='skills'){
      filters.push({id:'signature',label:'시그니처'},{id:'neutral',label:'중립'});
    }
    filters.forEach(ft=>{
      const btn=document.createElement('button');btn.className='btn btn-s';
      btn.style.cssText=`padding:3px 10px;font-size:.7rem;${f===ft.id?'border-color:#ffd700;color:#ffd700;':''}`;
      btn.textContent=ft.label;btn.onclick=()=>this.renderCodex(ft.id);fd.appendChild(btn);
    });
    // grid clear + 분기 렌더
    const grid=document.getElementById('codex-grid');grid.innerHTML='';
    if(k==='skills') this._renderCodexSkills(f, grid);
    else             this._renderCodexUnits(f, grid);
  },
  // 동료 카드 (UNITS) — 옛 logic 보존
  _renderCodexUnits(f, grid){
    const owned=new Set(this.deck.map(c=>c.id));
    let pool=UNITS.filter(u=>!u.id.startsWith('h_'));
    if(f==='owned')pool=pool.filter(u=>owned.has(u.id));
    else if(f==='missing')pool=pool.filter(u=>!owned.has(u.id));
    else if(['bronze','silver','gold','legendary','divine'].includes(f))pool=pool.filter(u=>u.rarity===f);
    const total=UNITS.filter(u=>!u.id.startsWith('h_')).length;
    const ownedCount=UNITS.filter(u=>!u.id.startsWith('h_')&&owned.has(u.id)).length;
    const pct=Math.floor(ownedCount/total*100);
    const summary=document.createElement('div');
    summary.style.cssText='width:100%;text-align:center;font-size:1rem;color:#ffd700;padding:10px;font-weight:700;letter-spacing:.05em;';
    summary.innerHTML=`🛡 동료 수집 <span style="color:#fff;">${ownedCount}</span> / ${total} <span style="color:#aaa;font-size:.8rem;">(${pct}%)</span>`;
    grid.appendChild(summary);
    if(!pool.length){
      const empty=document.createElement('div');
      empty.style.cssText='color:#555;font-size:.85rem;padding:20px;width:100%;text-align:center;';
      empty.textContent='해당 조건의 동료가 없습니다';
      grid.appendChild(empty);
      return;
    }
    pool.forEach(u=>{
      const have=owned.has(u.id);
      let el;
      if(have){
        el=mkCardElV4(u);
      }else{
        el=document.createElement('div');
        el.className='card-back';
        el.title=`미수집 — 클릭하여 정보 보기`;
      }
      el.onclick=()=>this.showCodexDetail(u,have);
      grid.appendChild(el);
    });
  },
  // 스킬 카드 (SKILLS_DB) — 시그니처 + 중립 모두 (2026-05-10 신규)
  // 수집 정의 (V1 단순): 영입한 동료의 bundledSkillIds 안 시그니처 + 보유 중립 스킬 (deck.skills 가 있다면)
  _renderCodexSkills(f, grid){
    const SKILLS = (typeof SKILLS_DB !== 'undefined' ? SKILLS_DB : (RoF.Data && RoF.Data.SKILLS) || []);
    if(!SKILLS.length){
      grid.innerHTML='<div style="color:#555;padding:20px;width:100%;text-align:center;">스킬 데이터 없음</div>';
      return;
    }
    // 수집 = 보유 동료의 시그니처 + (보유한 중립 스킬 — 현재 시스템 미정 → 빈 set)
    const ownedUnitIds=new Set(this.deck.map(c=>c.id));
    const ownedSkills=new Set();
    SKILLS.forEach(s=>{
      if(s.bundledByUnit && ownedUnitIds.has(s.bundledByUnit)) ownedSkills.add(s.id);
    });
    let pool=SKILLS.slice();
    if(f==='owned')        pool=pool.filter(s=>ownedSkills.has(s.id));
    else if(f==='missing') pool=pool.filter(s=>!ownedSkills.has(s.id));
    else if(['bronze','silver','gold','legendary','divine'].includes(f)) pool=pool.filter(s=>s.rarity===f);
    else if(f==='signature') pool=pool.filter(s=>!!s.bundledByUnit);
    else if(f==='neutral')   pool=pool.filter(s=>!s.bundledByUnit);
    // Summary 헤더
    const total=SKILLS.length;
    const sigCount=SKILLS.filter(s=>!!s.bundledByUnit).length;
    const neuCount=total-sigCount;
    const ownedCount=ownedSkills.size;
    const summary=document.createElement('div');
    summary.style.cssText='width:100%;text-align:center;font-size:1rem;color:#ffd700;padding:10px;font-weight:700;letter-spacing:.05em;';
    summary.innerHTML=`📜 스킬 <span style="color:#fff;">${total}</span> · 시그니처 <span style="color:#fff;">${sigCount}</span> · 중립 <span style="color:#fff;">${neuCount}</span> · 수집 <span style="color:#fff;">${ownedCount}</span>`;
    grid.appendChild(summary);
    if(!pool.length){
      const empty=document.createElement('div');
      empty.style.cssText='color:#555;font-size:.85rem;padding:20px;width:100%;text-align:center;';
      empty.textContent='해당 조건의 스킬이 없습니다';
      grid.appendChild(empty);
      return;
    }
    pool.forEach(s=>{
      const have=ownedSkills.has(s.id);
      let el;
      if(have){
        el=mkCardElV4(s);
      }else{
        el=document.createElement('div');
        el.className='card-back';
        el.title=`미수집 — 클릭하여 정보 보기`;
      }
      el.onclick=()=>this.showCodexDetail(s,have);
      grid.appendChild(el);
    });
  },
  // 2026-06-15: PHASE 6 필드 마이그레이션 — 유닛/스킬 공통. 옛 11스탯 소문자 스키마(atk/hp/spd/nrg/luck/eva/meva/skillDesc)
  //   는 PHASE 6(대문자 ATK/HP/NEED_SOUL + ability/keywords/dmgType)로 폐기되어 모달이 전부 'undefined' 노출하던 버그 수정.
  //   kind-aware: ◇영혼 항상 / ⚔ATK ♥HP 는 unit 만(스펠은 05-design ATK/HP 미표시) / 키워드 알약(정본 카드 요소).
  _CODEX_KIND_KO: {unit:'유닛', 'spell-target':'단일 주문', 'spell-aoe':'광역 주문', 'attach-hero':'영웅 부착', 'attach-unit':'유닛 부착', hero:'영웅'},
  _CODEX_DMG_KO:  {melee:'근접', ranged:'원거리', magic:'마법'},
  _CODEX_KW_KO:   {taunt:'수호자', battlecry:'전투의 함성', deathrattle:'죽음의 메아리', aura:'오라', dispel:'해제', retain:'보존', innate:'숙명', exhaust:'소멸', ethereal:'덧없음', first_only:'단발', evade_once:'회피'},
  showCodexDetail(u,owned){
    const m=document.getElementById('detail-modal');
    const ct=document.getElementById('detail-content');
    const elemColor=ELEM_COLOR[u.element]||'#aaa';
    const isUnit=(u.kind==='unit');
    const icon=u.icon||ELEM_ICON[u.element]||'❔';
    const kindL=this._CODEX_KIND_KO[u.kind]||u.kind||'';
    const dmgL=this._CODEX_DMG_KO[u.dmgType]||'';
    // 능력치 블록 (kind-aware) — 빈 값은 0 으로, undefined 노출 방지
    const stats=[];
    if(u.NEED_SOUL!=null) stats.push(`<span style="color:#b083e0;">◇ 영혼 ${u.NEED_SOUL}</span>`);
    if(isUnit){
      stats.push(`<span class="st-atk">⚔ 공격 ${u.ATK!=null?u.ATK:0}</span>`);
      stats.push(`<span class="st-hp">♥ 체력 ${u.HP!=null?u.HP:0}</span>`);
      if(u.DEF) stats.push(`<span class="st-def">🛡 보호막 ${u.DEF}</span>`);
    }
    if(dmgL) stats.push(`<span style="color:#88ddff;">${dmgL}</span>`);
    const kwPills=(Array.isArray(u.keywords)?u.keywords:[]).map(k=>
      `<span style="padding:1px 8px;border-radius:9px;background:rgba(155,131,224,.18);border:1px solid #6a5a9a;color:#cdbff0;font-size:.68rem;">${this._CODEX_KW_KO[k]||k}</span>`).join('');
    ct.innerHTML=`
      <div style="text-align:center;margin-bottom:10px;">
        <div style="font-size:2.5rem;">${icon}</div>
        <div style="font-size:1.2rem;color:#fff;font-weight:bold;">${u.name||''}</div>
        <div style="font-size:.8rem;color:#aaa;">${kindL}${u.role?` · ${ROLE_L[u.role]||u.role}`:''} · ${R_LABEL[u.rarity]||u.rarity||''}</div>
        <div style="font-size:.8rem;"><span style="color:${elemColor};">${ELEM_ICON[u.element]||''} ${ELEM_L[u.element]||'무속성'}</span>${u.race?` · ${u.race}`:''}</div>
        <div style="font-size:.8rem;margin-top:4px;color:${owned?'#44ff88':'#ff4444'};">${owned?'✅ 보유 중':'❌ 미보유'}</div>
      </div>
      <div style="border-top:1px solid #333;padding-top:8px;margin-bottom:8px;">
        <div style="font-size:.85rem;color:#fff;margin-bottom:4px;">📊 능력치</div>
        <div style="display:flex;flex-wrap:wrap;gap:6px;font-size:.8rem;align-items:center;">${stats.join('')}</div>
        ${kwPills?`<div style="display:flex;flex-wrap:wrap;gap:4px;margin-top:6px;">${kwPills}</div>`:''}
      </div>
      ${(u.ability||u.desc)?`<div style="border-top:1px solid #333;padding-top:8px;">
        <div style="font-size:.85rem;color:#fff;margin-bottom:4px;">⚡ 효과</div>
        ${u.ability?`<div style="font-size:.78rem;color:#ddd;line-height:1.45;">${u.ability}</div>`:''}
        ${u.desc?`<div style="font-size:.72rem;color:#999;font-style:italic;margin-top:6px;">"${u.desc}"</div>`:''}
      </div>`:''}
      ${owned?'':`<div style="border-top:1px solid #333;padding-top:8px;margin-top:8px;">
        <div style="font-size:.85rem;color:#ffd700;margin-bottom:4px;">🗺️ 획득 경로</div>
        <div style="font-size:.75rem;color:#ddd;line-height:1.5;">${this._codexAcquireHint(u)}</div>
      </div>`}`;
    m.classList.add('active');
  },

  /** 2026-05-02: 미수집 카드 클릭 시 표시할 등급별 generic 획득 경로 힌트.
   *  카드 데이터에 별도 acquireHint 필드 없으므로 rarity 기반.
   *  monetization v2.1 § 0 가챠 폐기 — 모두 확정 지급 경로. */
  _codexAcquireHint(u){
    const r=u.rarity||'bronze';
    const role=u.role||'attack';
    const HINTS={
      bronze:    '🍺 선술집에서 자주 만나볼 수 있습니다.<br>전투 보상 으로도 종종 등장.',
      silver:    '🍺 선술집에서 만나거나 전투 보상으로 획득 가능.<br>리그 시즌 종료 시 확정 보상 후보.',
      gold:      '🍺 선술집에서 드물게 등장.<br>🏆 골드 리그 이상 시즌 보상 / 업적 확정 보상.',
      legendary: '🌌 차원의 균열 보상 / 절대신 도전 / 시즌 최고 업적 확정 보상.<br>선술집에서는 거의 등장하지 않습니다.',
      divine:    '👑 절대신 클리어 시 영웅에게 부여 / 시즌 최고 업적 확정.<br>일반 획득 경로로는 만날 수 없는 신성 영역.',
    };
    let hint=HINTS[r]||HINTS.bronze;
    // 영웅 카드 (h_*) 는 별도 안내
    if(u.id&&u.id.startsWith('h_')){
      hint='⚜️ 영웅 카드 — 캐릭터 생성 시 원소·역할·성별 선택으로 정해집니다.<br>전직 시스템(예정) 으로 다른 영웅 길로 전환 가능.';
    }
    return hint;
  },

  showDeckView(){
    // 2026-05-09 — 옛 deckview 폐기, 새 formation 화면 (전열 정비) 으로 redirect.
    // codex (생명의 서) 분리 작업은 별도 phase. 일단 동료/비전 탭은 formation 에서.
    if(RoF.Formation && RoF.Formation.show){ RoF.Formation.show(); return; }
    // fallback (Formation 모듈 미로드 — 안전망)
    UI.show('deckview-screen');
    this._dvTab='deck';this.showDeckTab();
    document.getElementById('dv-name').textContent=`👤 ${Auth.heroName||Auth.user}`;
    document.getElementById('dv-slots').textContent=this.getCommandSlots();
    document.getElementById('dv-rslots').textContent=this.getRelicSlots();
    const npc=this.getNpc('library');
    const existing=document.getElementById('lib-npc');if(existing)existing.remove();
    document.getElementById('tab-deck').parentElement.insertAdjacentHTML('afterend',`<div id="lib-npc">${this.renderNpcBar('library')}</div>`);
    // Section title counts (N/M)
    const totalUnits=UNITS.filter(u=>!u.id.startsWith('h_')).length;
    const ownedUnits=this.deck.filter(c=>!c.isHero).length;
    const ownedSk=(this.ownedSkills||[]).length, totalSk=SKILLS_DB.length;
    const ownedRl=(this.ownedRelics||[]).length, totalRl=RELICS_DB.length;
    document.querySelectorAll('#deck-tab .dv-title').forEach(e=>e.remove());
    // Onboarding (empty starter)
    const onb=document.getElementById('dv-onboarding');if(onb)onb.remove();
    if(ownedUnits===0&&ownedSk===0&&ownedRl===0){
      const ob=document.createElement('div');ob.id='dv-onboarding';ob.className='dv-onboarding';
      ob.innerHTML=`💡 첫 동료를 영입하세요<br><span>선술집에서 5골드로 브론즈 동료 영입 가능</span><br><button class="btn btn-s" data-action="game.showTavern" style="margin-top:6px;">🍺 선술집으로</button>`;
      document.getElementById('deck-tab').prepend(ob);
    }
    // Units
    const g=document.getElementById('dv-grid');g.innerHTML='';
    g.insertAdjacentHTML('beforebegin',`<div class="dv-title">👥 동료 (${ownedUnits}/${totalUnits})</div>`);
    this.deck.forEach(c=>{
      const el=mkCardElV4(c);  // Step 5A-1: V4 프레임 (2026-04-21)
      // 2026-04-27: 클릭 → 중앙 확대 focus (전투 char-focus 와 동형). 기존 showCardDetail 모달 폐기.
      el.onclick=()=>this.showDeckCardFocus(c);
      g.appendChild(el);
    });
    const emptyU=Math.max(0,Math.min(6,totalUnits-ownedUnits));
    const hintN=ownedUnits===0?3:0;  // P0-2: 동료 0명일 때만 첫 3칸을 힌트로 승격
    for(let i=0;i<emptyU;i++){
      if(i<hintN){
        g.insertAdjacentHTML('beforeend','<div class="empty-slot hint" title="선술집에서 영입"><span class="es-icon">⚔</span><span class="es-label">선술집에서<br>영입</span></div>');
      } else {
        g.insertAdjacentHTML('beforeend','<div class="empty-slot" title="동료를 영입하면 여기에 표시됩니다">?</div>');
      }
    }
    // Skills
    const sg=document.getElementById('dv-skills');sg.innerHTML='';
    sg.insertAdjacentHTML('beforebegin',`<div class="dv-title">💎 비전 (${ownedSk}/${totalSk})</div>`);
    const skills=this.ownedSkills||[];
    if(!skills.length){
      for(let i=0;i<6;i++)sg.insertAdjacentHTML('beforeend','<div class="empty-slot" title="전투 보상으로 비전을 획득하세요">?</div>');
    } else {
      skills.forEach(sk=>{
        const el=mkRelicEl(sk);  // V4 로 kind 자동 판별 (effect 있으면 '비전')
        // Show equipped status
        const equipped=this.deck.find(c=>(c.equips||[]).some(e=>e.uid===sk.uid));
        if(equipped){
          const tag=document.createElement('div');tag.style.cssText='text-align:center;font-size:.65rem;color:#44ff88;margin-top:2px;';
          tag.textContent=`→ ${equipped.icon}${equipped.name}에 장착`;
          el.appendChild(tag);
        } else {
          const tag=document.createElement('div');tag.style.cssText='text-align:center;font-size:.65rem;color:#888;margin-top:2px;';
          tag.textContent='미장착 (클릭하여 장착)';
          el.appendChild(tag);
        }
        el.onclick=()=>{
          if(equipped){
            // Unequip
            UI.modal('비전 해제',`${equipped.icon}${equipped.name}에서 ${sk.icon}${sk.name}을 해제하시겠습니까?`,()=>{
              equipped.equips=equipped.equips.filter(e=>e.uid!==sk.uid);
              SFX.play('click');this.persist();this.showDeckView();
            });
          } else {
            // Equip to a unit
            this.equipOwnedSkill(sk);
          }
        };
        sg.appendChild(el);
      });
    }
    // Relics
    const rg=document.getElementById('dv-relics');rg.innerHTML='';
    rg.insertAdjacentHTML('beforebegin',`<div class="dv-title">🏺 유물 (${ownedRl}/${totalRl})</div>`);
    if(!this.ownedRelics||!this.ownedRelics.length){
      for(let i=0;i<6;i++)rg.insertAdjacentHTML('beforeend','<div class="empty-slot" title="차원의 균열에서 유물을 획득하세요">?</div>');
    } else {
      this.ownedRelics.forEach(r=>{
        const el=mkRelicEl(r);
        el.onclick=()=>this.showRelicDetail(r);
        rg.appendChild(el);
      });
    }
  },

  equipOwnedSkill(sk){
    const modal=document.getElementById('equip-modal');
    document.getElementById('equip-title').textContent='비전 장착 대상 선택';
    document.getElementById('equip-skill-info').textContent=`${sk.icon} ${sk.name}: ${sk.desc}`;
    const targets=document.getElementById('equip-targets');targets.innerHTML='';
    this.deck.forEach(c=>{
      const d=document.createElement('div');d.className=`deck-mini ${c.rarity||'bronze'}`;d.style.cursor='pointer';
      d.innerHTML=`<div class="dm-icon">${c.icon}</div><div class="dm-name">${c.isHero?'⭐':''}${c.name}</div>`;
      d.onclick=()=>{
        c.equips=c.equips||[];
        c.equips.push({icon:sk.icon,name:sk.name,id:sk.id,uid:sk.uid});
        applySkillToUnit(sk,c);
        modal.classList.remove('active');SFX.play('magic');this.persist();this.showDeckView();
      };targets.appendChild(d);});
    modal.classList.add('active');
  },

  // 2026-04-27: showCardDetail (detail-modal 텍스트 설명창) 폐기.
  //   대체: showDeckCardFocus — 전투 char-focus 와 동형 UI (중앙 V4 카드 확대 + 보유 스킬카드 row).
  //   trait 시스템 / freePoints 분배 / 비전 해제 버튼 모두 폐기. 단련은 castle 에서.
  showDeckCardFocus(c){
    const overlay = document.getElementById('dv-focus');
    if(!overlay) return;
    const mainCard = overlay.querySelector('.dvf-main-card');
    const skillRow = overlay.querySelector('.dvf-skill-row');
    if(!mainCard || !skillRow) return;

    // 1) 중앙 카드 — V4 컴포넌트로 currentHp/curNrg 반영해서 큰 사이즈로 렌더.
    mainCard.innerHTML='';
    const cardEl = mkCardElV4(c);
    mainCard.appendChild(cardEl);

    // 2) 스킬 row — 전투 char-focus 와 동일하게 buildUnitSkillSet 결과 표시.
    //    Battle.buildUnitSkillSet 가 export 되어 있으면 사용 (정확). 미정의 시 기본 스킬만 표시.
    let skills = [];
    try {
      if(window.Battle && typeof Battle.buildUnitSkillSet === 'function'){
        skills = Battle.buildUnitSkillSet(c).filter(s=>s && s.passive!==true);
      }
    } catch(e){ skills = []; }

    skillRow.innerHTML='';
    if(!skills.length){
      const empty=document.createElement('div');
      empty.className='dvf-skill-empty';
      empty.textContent='전투 시 사용할 스킬이 없습니다.';
      skillRow.appendChild(empty);
    } else {
      skills.forEach(sk=>{
        const slot=document.createElement('div');
        slot.className='dvf-skill-card';
        const skImg = (typeof Battle !== 'undefined' && Battle.resolveImg) ? Battle.resolveImg(sk.imgKey) : null;
        slot.innerHTML=`
          <div class="bsc-card-img">${skImg?`<img src="${skImg}" alt="">`:''}</div>
          <div class="bsc-cost">⚡${sk.cost ?? 0}${sk.tpCost > 1 ? ' TP' + sk.tpCost : ''}</div>
          <div class="bsc-name">${sk.name||''}</div>
          <div class="bsc-desc">${sk.desc||''}</div>`;
        skillRow.appendChild(slot);
      });
    }

    overlay.classList.add('active');
  },
  closeDeckCardFocus(){
    const overlay = document.getElementById('dv-focus');
    if(overlay) overlay.classList.remove('active');
  },

  showRelicDetail(r){
    const m=document.getElementById('detail-modal');
    const ct=document.getElementById('detail-content');
    ct.innerHTML=`
      <div style="text-align:center;margin-bottom:10px;">
        <div style="font-size:2.5rem;">${r.icon}</div>
        <div style="font-size:1.2rem;color:#fff;font-weight:bold;">${r.name}</div>
        <div style="font-size:.8rem;color:#aaa;">유물 · ${R_LABEL[r.rarity]||''}</div>
      </div>
      <div style="border-top:1px solid #333;padding-top:8px;">
        <div style="font-size:.85rem;color:#ddd;">${r.desc}</div>
      </div>
    `;
    m.classList.add('active');
  },

  // ---- TAVERN (용병 고용) ----
  equipSkill(skillData){
    const modal=document.getElementById('equip-modal');
    document.getElementById('equip-skill-info').textContent=`${skillData.icon} ${skillData.name}: ${skillData.desc}`;
    const targets=document.getElementById('equip-targets');targets.innerHTML='';
    this.deck.forEach(c=>{
      const d=document.createElement('div');d.className=`deck-mini ${c.rarity||'bronze'}`;d.style.cursor='pointer';
      d.innerHTML=`<div class="dm-icon">${c.icon}</div><div class="dm-name">${c.isHero?'⭐':''}${c.name}</div>`;
      d.onclick=()=>{
        applySkillToUnit(skillData,c);
        c.equips=c.equips||[];c.equips.push({icon:skillData.icon,name:skillData.name,id:skillData.id});
        modal.classList.remove('active');SFX.play('magic');
      };targets.appendChild(d);});
    modal.classList.add('active');
  },
});
